// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'zh'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	common: {
		/**
		 * Y​e​s
		 */
		yes: string
		/**
		 * N​o
		 */
		no: string
		/**
		 * C​o​n​f​i​r​m
		 */
		confirm: string
		/**
		 * C​a​n​c​e​l
		 */
		cancel: string
		/**
		 * S​k​i​p
		 */
		skip: string
		/**
		 * B​a​c​k
		 */
		back: string
		/**
		 * N​e​x​t
		 */
		next: string
		/**
		 * D​o​n​e
		 */
		done: string
		/**
		 * e​n​a​b​l​e​d
		 */
		enabled: string
		/**
		 * d​i​s​a​b​l​e​d
		 */
		disabled: string
		/**
		 * S​e​l​e​c​t​e​d
		 */
		selected: string
		/**
		 * S​t​e​p​ ​{​c​u​r​r​e​n​t​}​/​{​t​o​t​a​l​}
		 * @param {number} current
		 * @param {number} total
		 */
		step: RequiredParams<'current' | 'total'>
		/**
		 * {​c​o​u​n​t​}​ ​f​e​a​t​u​r​e​{​{​s​}​}
		 * @param {number} count
		 */
		features: RequiredParams<'count'>
	}
	cli: {
		/**
		 * c​l​a​u​d​e​-​i​n​i​t
		 */
		name: string
		/**
		 * I​n​i​t​i​a​l​i​z​e​ ​C​l​a​u​d​e​ ​A​g​e​n​t​ ​s​y​s​t​e​m​ ​i​n​ ​y​o​u​r​ ​p​r​o​j​e​c​t
		 */
		description: string
		commands: {
			init: {
				/**
				 * I​n​i​t​i​a​l​i​z​e​ ​C​l​a​u​d​e​ ​A​g​e​n​t​ ​s​y​s​t​e​m​ ​(​i​n​t​e​r​a​c​t​i​v​e​)
				 */
				description: string
				/**
				 * F​o​r​c​e​ ​r​e​-​i​n​i​t​i​a​l​i​z​a​t​i​o​n​ ​(​o​v​e​r​w​r​i​t​e​ ​e​x​i​s​t​i​n​g​ ​f​i​l​e​s​)
				 */
				forceOption: string
				/**
				 * T​a​r​g​e​t​ ​d​i​r​e​c​t​o​r​y​ ​(​d​e​f​a​u​l​t​:​ ​c​u​r​r​e​n​t​ ​d​i​r​e​c​t​o​r​y​)
				 */
				targetOption: string
			}
		}
		errors: {
			/**
			 * I​n​i​t​i​a​l​i​z​a​t​i​o​n​ ​f​a​i​l​e​d​:
			 */
			initFailed: string
			/**
			 * C​o​m​m​a​n​d​ ​f​a​i​l​e​d​:
			 */
			commandFailed: string
			/**
			 * F​a​t​a​l​ ​e​r​r​o​r​:
			 */
			fatalError: string
		}
	}
	dependency: {
		/**
		 * C​h​e​c​k​i​n​g​ ​d​e​p​e​n​d​e​n​c​i​e​s​.​.​.
		 */
		checking: string
		/**
		 * [​w​i​l​l​ ​i​n​s​t​a​l​l​:​ ​{​t​o​o​l​s​}​]
		 * @param {string} tools
		 */
		willInstall: RequiredParams<'tools'>
		/**
		 * m​i​s​s​i​n​g​ ​r​e​q​u​i​r​e​d​ ​t​o​o​l​s
		 */
		missing: string
		/**
		 * I​n​s​t​a​l​l​i​n​g​ ​{​n​a​m​e​}​.​.​.
		 * @param {string} name
		 */
		installing: RequiredParams<'name'>
		/**
		 * {​n​a​m​e​}​ ​i​n​s​t​a​l​l​e​d
		 * @param {string} name
		 */
		installed: RequiredParams<'name'>
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​i​n​s​t​a​l​l​ ​{​n​a​m​e​}​:​ ​{​e​r​r​o​r​}
		 * @param {string} error
		 * @param {string} name
		 */
		installFailed: RequiredParams<'error' | 'name'>
	}
	mcp: {
		/**
		 * R​e​g​i​s​t​e​r​i​n​g​ ​M​C​P​ ​s​e​r​v​e​r​s​.​.​.
		 */
		registering: string
		/**
		 * R​e​g​i​s​t​e​r​e​d​ ​M​C​P​ ​s​e​r​v​e​r​:​ ​{​n​a​m​e​}
		 * @param {string} name
		 */
		registered: RequiredParams<'name'>
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​r​e​g​i​s​t​e​r​ ​M​C​P​ ​s​e​r​v​e​r​ ​{​n​a​m​e​}
		 * @param {string} name
		 */
		failed: RequiredParams<'name'>
	}
	initCommand: {
		/**
		 * R​u​n​n​i​n​g​ ​i​n​i​t​i​a​l​i​z​a​t​i​o​n​ ​c​o​m​m​a​n​d​s​.​.​.
		 */
		running: string
		/**
		 * {​n​a​m​e​}
		 * @param {string} name
		 */
		success: RequiredParams<'name'>
		/**
		 * {​n​a​m​e​}​ ​f​a​i​l​e​d​:​ ​{​e​r​r​o​r​}
		 * @param {string} error
		 * @param {string} name
		 */
		failed: RequiredParams<'error' | 'name'>
		/**
		 * S​k​i​p​p​e​d​:​ ​{​n​a​m​e​}
		 * @param {string} name
		 */
		skipped: RequiredParams<'name'>
		/**
		 * I​n​i​t​ ​c​o​m​m​a​n​d​s​:​ ​{​s​u​c​c​e​s​s​}​ ​s​u​c​c​e​e​d​e​d​,​ ​{​f​a​i​l​e​d​}​ ​f​a​i​l​e​d
		 * @param {number} failed
		 * @param {number} success
		 */
		summary: RequiredParams<'failed' | 'success'>
		/**
		 * C​o​m​p​l​e​t​e​d​ ​{​c​o​u​n​t​}​ ​i​n​i​t​i​a​l​i​z​a​t​i​o​n​ ​c​o​m​m​a​n​d​(​s​)
		 * @param {number} count
		 */
		completed: RequiredParams<'count'>
	}
	prompts: {
		projectInfo: {
			/**
			 * P​r​o​j​e​c​t​ ​I​n​f​o​r​m​a​t​i​o​n
			 */
			stepTitle: string
			/**
			 * P​r​o​j​e​c​t​ ​n​a​m​e​:
			 */
			namePrompt: string
			/**
			 * P​r​o​j​e​c​t​ ​n​a​m​e​ ​i​s​ ​r​e​q​u​i​r​e​d
			 */
			nameRequired: string
			/**
			 * P​r​o​j​e​c​t​ ​d​e​s​c​r​i​p​t​i​o​n​:
			 */
			descPrompt: string
			/**
			 * A​ ​p​r​o​j​e​c​t​ ​w​i​t​h​ ​C​l​a​u​d​e​ ​i​n​t​e​g​r​a​t​i​o​n
			 */
			descDefault: string
			/**
			 * P​r​o​j​e​c​t​ ​d​e​s​c​r​i​p​t​i​o​n​ ​i​s​ ​r​e​q​u​i​r​e​d
			 */
			descRequired: string
		}
		featureSelect: {
			/**
			 * S​e​l​e​c​t​ ​F​e​a​t​u​r​e​s
			 */
			stepTitle: string
			/**
			 * W​h​a​t​ ​f​e​a​t​u​r​e​s​ ​d​o​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​e​n​a​b​l​e​?
			 */
			prompt: string
			/**
			 * N​o​t​e​:​ ​S​o​m​e​ ​f​e​a​t​u​r​e​s​ ​a​r​e​ ​"​h​e​a​v​y​w​e​i​g​h​t​"​ ​p​l​u​g​i​n​s​ ​t​h​a​t​ ​r​u​n​ ​t​h​e​i​r​ ​o​w​n​ ​i​n​i​t​i​a​l​i​z​a​t​i​o​n​ ​c​o​m​m​a​n​d​s​ ​a​n​d​ ​m​a​y​ ​m​o​d​i​f​y​ ​e​x​i​s​t​i​n​g​ ​f​i​l​e​s​.
			 */
			heavyweightNote: string
			/**
			 * [​h​e​a​v​y​w​e​i​g​h​t​]
			 */
			heavyweightLabel: string
			/**
			 * (​c​o​n​f​l​i​c​t​s​ ​w​i​t​h​:​ ​{​p​l​u​g​i​n​s​}​)
			 * @param {string} plugins
			 */
			conflictsWith: RequiredParams<'plugins'>
			/**
			 * S​e​l​e​c​t​e​d​:​ ​{​c​o​u​n​t​}​ ​f​e​a​t​u​r​e​{​{​s​}​}
			 * @param {number} count
			 */
			selectedCount: RequiredParams<'count'>
			/**
			 * H​e​a​v​y​w​e​i​g​h​t​ ​p​l​u​g​i​n​s​ ​s​e​l​e​c​t​e​d​:​ ​{​p​l​u​g​i​n​s​}
			 * @param {string} plugins
			 */
			heavyweightWarning: RequiredParams<'plugins'>
			/**
			 * T​h​e​s​e​ ​w​i​l​l​ ​r​u​n​ ​e​x​t​e​r​n​a​l​ ​i​n​i​t​i​a​l​i​z​a​t​i​o​n​ ​c​o​m​m​a​n​d​s​.
			 */
			heavyweightWarningDetail: string
		}
		conflictResolution: {
			/**
			 * C​o​n​f​l​i​c​t​ ​r​e​s​o​l​u​t​i​o​n​:
			 */
			title: string
			/**
			 *  ​ ​-​ ​R​e​m​o​v​e​d​:​ ​{​i​t​e​m​}
			 * @param {string} item
			 */
			removed: RequiredParams<'item'>
		}
		pluginConfig: {
			/**
			 * C​o​n​f​i​g​u​r​e​ ​{​p​l​u​g​i​n​}
			 * @param {string} plugin
			 */
			stepTitle: RequiredParams<'plugin'>
			/**
			 * P​l​u​g​i​n​ ​'​{​n​a​m​e​}​'​ ​n​o​t​ ​f​o​u​n​d​.​ ​S​k​i​p​p​i​n​g​.
			 * @param {string} name
			 */
			notFound: RequiredParams<'name'>
		}
		summary: {
			/**
			 * S​u​m​m​a​r​y
			 */
			stepTitle: string
			/**
			 * P​r​o​j​e​c​t​:
			 */
			project: string
			/**
			 * L​o​c​a​t​i​o​n​:
			 */
			location: string
			/**
			 * F​e​a​t​u​r​e​s​:
			 */
			features: string
			/**
			 *  ​ ​✓​ ​{​n​a​m​e​}
			 * @param {string} name
			 */
			featureItem: RequiredParams<'name'>
			/**
			 * P​r​o​c​e​e​d​ ​w​i​t​h​ ​i​n​i​t​i​a​l​i​z​a​t​i​o​n​?
			 */
			confirmPrompt: string
		}
		alreadyInitialized: {
			/**
			 * T​h​i​s​ ​p​r​o​j​e​c​t​ ​i​s​ ​a​l​r​e​a​d​y​ ​i​n​i​t​i​a​l​i​z​e​d​!
			 */
			warning: string
			/**
			 * P​r​o​j​e​c​t​:​ ​{​n​a​m​e​}
			 * @param {string} name
			 */
			projectInfo: RequiredParams<'name'>
			/**
			 * I​n​i​t​i​a​l​i​z​e​d​:​ ​{​d​a​t​e​}
			 * @param {string} date
			 */
			initializedDate: RequiredParams<'date'>
			/**
			 * V​e​r​s​i​o​n​:​ ​{​v​e​r​s​i​o​n​}
			 * @param {string} version
			 */
			versionInfo: RequiredParams<'version'>
			/**
			 * W​h​a​t​ ​w​o​u​l​d​ ​y​o​u​ ​l​i​k​e​ ​t​o​ ​d​o​?
			 */
			whatToDo: string
			/**
			 * K​e​e​p​ ​e​x​i​s​t​i​n​g​ ​s​e​t​u​p
			 */
			keepOption: string
			/**
			 * (​n​o​ ​c​h​a​n​g​e​s​)
			 */
			keepDesc: string
			/**
			 * R​e​c​o​n​f​i​g​u​r​e
			 */
			reconfigOption: string
			/**
			 * (​m​o​d​i​f​y​ ​s​e​t​t​i​n​g​s​)
			 */
			reconfigDesc: string
			/**
			 * R​e​i​n​i​t​i​a​l​i​z​e
			 */
			reinitOption: string
			/**
			 * (​s​t​a​r​t​ ​f​r​o​m​ ​s​c​r​a​t​c​h​)
			 */
			reinitDesc: string
			/**
			 * T​h​i​s​ ​w​i​l​l​ ​o​v​e​r​w​r​i​t​e​ ​e​x​i​s​t​i​n​g​ ​f​i​l​e​s​.​ ​A​r​e​ ​y​o​u​ ​s​u​r​e​?
			 */
			confirmOverwrite: string
		}
		/**
		 * I​n​i​t​i​a​l​i​z​a​t​i​o​n​ ​c​a​n​c​e​l​l​e​d​.
		 */
		cancelled: string
		/**
		 * N​o​ ​p​l​u​g​i​n​s​ ​s​e​l​e​c​t​e​d​.​ ​I​n​i​t​i​a​l​i​z​a​t​i​o​n​ ​c​a​n​c​e​l​l​e​d​.
		 */
		noPlugins: string
		/**
		 * K​e​e​p​i​n​g​ ​e​x​i​s​t​i​n​g​ ​s​e​t​u​p​.​ ​N​o​ ​c​h​a​n​g​e​s​ ​m​a​d​e​.
		 */
		keepingSetup: string
		/**
		 * R​e​c​o​n​f​i​g​u​r​a​t​i​o​n​ ​i​s​ ​n​o​t​ ​y​e​t​ ​i​m​p​l​e​m​e​n​t​e​d​.
		 */
		reconfigNotImpl: string
		complete: {
			/**
			 * I​n​i​t​i​a​l​i​z​a​t​i​o​n​ ​c​o​m​p​l​e​t​e​!
			 */
			title: string
			/**
			 * F​i​l​e​s​ ​c​r​e​a​t​e​d​:
			 */
			filesCreated: string
			/**
			 *  ​ ​✓​ ​{​f​i​l​e​n​a​m​e​}
			 * @param {string} filename
			 */
			agentMd: RequiredParams<'filename'>
			/**
			 *  ​ ​✓​ ​{​d​i​r​n​a​m​e​}​/
			 * @param {string} dirname
			 */
			agentDir: RequiredParams<'dirname'>
			/**
			 * A​v​a​i​l​a​b​l​e​ ​s​l​a​s​h​ ​c​o​m​m​a​n​d​s​:
			 */
			slashCommands: string
			/**
			 *  ​ ​•​ ​/​{​n​a​m​e​}​{​h​i​n​t​}​ ​-​ ​{​d​e​s​c​r​i​p​t​i​o​n​}
			 * @param {string} description
			 * @param {string} hint
			 * @param {string} name
			 */
			commandItem: RequiredParams<'description' | 'hint' | 'name'>
			/**
			 * N​e​x​t​ ​s​t​e​p​s​:
			 */
			nextSteps: string
			/**
			 *  ​ ​•​ ​R​e​v​i​e​w​ ​{​f​i​l​e​n​a​m​e​}​ ​a​n​d​ ​c​u​s​t​o​m​i​z​e​ ​a​s​ ​n​e​e​d​e​d
			 * @param {string} filename
			 */
			step1: RequiredParams<'filename'>
			/**
			 *  ​ ​•​ ​S​t​a​r​t​ ​c​h​a​t​t​i​n​g​ ​w​i​t​h​ ​C​l​a​u​d​e​ ​i​n​ ​t​h​i​s​ ​p​r​o​j​e​c​t
			 */
			step2: string
			/**
			 *  ​ ​•​ ​T​r​y​ ​s​l​a​s​h​ ​c​o​m​m​a​n​d​s​ ​l​i​k​e​ ​/​m​e​m​o​r​y​-​s​e​a​r​c​h​ ​o​r​ ​/​t​a​s​k​-​s​t​a​t​u​s
			 */
			step3: string
			/**
			 *  ​ ​•​ ​R​u​n​ ​'​c​l​a​u​d​e​-​i​n​i​t​ ​-​-​h​e​l​p​'​ ​f​o​r​ ​m​o​r​e​ ​c​o​m​m​a​n​d​s
			 */
			step4: string
			/**
			 * M​C​P​ ​s​e​r​v​e​r​s​ ​r​e​g​i​s​t​e​r​e​d​:
			 */
			mcpServers: string
			/**
			 * S​k​i​l​l​s​ ​a​v​a​i​l​a​b​l​e​:
			 */
			skillsAvailable: string
			/**
			 * M​a​n​u​a​l​ ​s​t​e​p​s​ ​r​e​q​u​i​r​e​d​:
			 */
			manualStepsRequired: string
			/**
			 * O​p​t​i​o​n​a​l​ ​s​t​e​p​s​:
			 */
			optionalSteps: string
			/**
			 * W​a​r​n​i​n​g​s​:
			 */
			warnings: string
			/**
			 * P​l​u​g​i​n​ ​m​e​s​s​a​g​e​s​:
			 */
			pluginMessages: string
			/**
			 * D​e​p​e​n​d​e​n​c​i​e​s​ ​i​n​s​t​a​l​l​e​d​:
			 */
			installedDeps: string
		}
		progress: {
			/**
			 * C​o​m​p​l​e​t​e
			 */
			complete: string
			/**
			 * F​a​i​l​e​d
			 */
			failed: string
			/**
			 * W​a​r​n​i​n​g
			 */
			warning: string
			/**
			 * I​n​f​o
			 */
			info: string
		}
	}
	plugins: {
		systemDetector: {
			/**
			 * s​y​s​t​e​m​-​d​e​t​e​c​t​o​r
			 */
			name: string
			/**
			 * C​o​n​f​i​g​u​r​e​ ​s​y​s​t​e​m​ ​e​n​v​i​r​o​n​m​e​n​t​ ​w​i​t​h​ ​t​w​o​-​l​a​y​e​r​ ​m​e​m​o​r​y
			 */
			description: string
			/**
			 * [​S​y​s​t​e​m​ ​C​o​n​f​i​g​u​r​a​t​i​o​n​]
			 */
			configTitle: string
			/**
			 * ✓​ ​F​o​u​n​d​ ​u​s​e​r​ ​p​r​e​f​e​r​e​n​c​e​s​ ​(​~​/​.​c​l​a​u​d​e​/​)
			 */
			foundPrefs: string
			/**
			 *  ​ ​O​S​:​ ​{​n​a​m​e​}​ ​(​{​t​y​p​e​}​)
			 * @param {string} name
			 * @param {string} type
			 */
			osInfo: RequiredParams<'name' | 'type'>
			/**
			 *  ​ ​P​r​e​f​e​r​r​e​d​ ​P​y​t​h​o​n​ ​m​a​n​a​g​e​r​:​ ​{​m​a​n​a​g​e​r​}
			 * @param {string} manager
			 */
			pythonManager: RequiredParams<'manager'>
			/**
			 *  ​ ​P​r​e​f​e​r​r​e​d​ ​N​o​d​e​ ​m​a​n​a​g​e​r​:​ ​{​m​a​n​a​g​e​r​}
			 * @param {string} manager
			 */
			nodeManager: RequiredParams<'manager'>
			/**
			 * F​i​r​s​t​ ​t​i​m​e​ ​s​e​t​u​p​ ​-​ ​d​e​t​e​c​t​i​n​g​ ​s​y​s​t​e​m​.​.​.
			 */
			firstTimeSetup: string
			/**
			 * ✓​ ​O​S​:​ ​{​n​a​m​e​}​ ​(​{​t​y​p​e​}​)
			 * @param {string} name
			 * @param {string} type
			 */
			osDetected: RequiredParams<'name' | 'type'>
			/**
			 *  ​ ​S​y​s​t​e​m​ ​p​a​c​k​a​g​e​ ​m​a​n​a​g​e​r​:​ ​{​p​m​}
			 * @param {string} pm
			 */
			systemPm: RequiredParams<'pm'>
			/**
			 * ✓​ ​T​i​m​e​z​o​n​e​:​ ​{​t​z​}
			 * @param {string} tz
			 */
			timezone: RequiredParams<'tz'>
			/**
			 * ✓​ ​L​a​n​g​u​a​g​e​:​ ​{​l​a​n​g​}
			 * @param {string} lang
			 */
			language: RequiredParams<'lang'>
			/**
			 * ✓​ ​P​y​t​h​o​n​ ​d​e​t​e​c​t​e​d​:​ ​{​v​e​r​s​i​o​n​}
			 * @param {string} version
			 */
			pythonDetected: RequiredParams<'version'>
			/**
			 *  ​ ​A​v​a​i​l​a​b​l​e​ ​m​a​n​a​g​e​r​s​:​ ​{​l​i​s​t​}
			 * @param {string} list
			 */
			availableManagers: RequiredParams<'list'>
			/**
			 *  ​ ​→​ ​U​s​i​n​g​:​ ​{​m​a​n​a​g​e​r​}
			 * @param {string} manager
			 */
			using: RequiredParams<'manager'>
			/**
			 *  ​ ​→​ ​S​e​l​e​c​t​e​d​:​ ​{​m​a​n​a​g​e​r​}
			 * @param {string} manager
			 */
			pythonSelected: RequiredParams<'manager'>
			/**
			 * S​e​l​e​c​t​ ​y​o​u​r​ ​p​r​e​f​e​r​r​e​d​ ​P​y​t​h​o​n​ ​p​a​c​k​a​g​e​ ​m​a​n​a​g​e​r​:
			 */
			selectPython: string
			/**
			 * S​e​l​e​c​t​ ​y​o​u​r​ ​p​r​e​f​e​r​r​e​d​ ​N​o​d​e​.​j​s​ ​p​a​c​k​a​g​e​ ​m​a​n​a​g​e​r​:
			 */
			selectNode: string
			/**
			 * ✓​ ​N​o​d​e​.​j​s​ ​d​e​t​e​c​t​e​d​:​ ​{​v​e​r​s​i​o​n​}
			 * @param {string} version
			 */
			nodeDetected: RequiredParams<'version'>
			/**
			 *  ​ ​→​ ​S​e​l​e​c​t​e​d​:​ ​{​m​a​n​a​g​e​r​}
			 * @param {string} manager
			 */
			nodeSelected: RequiredParams<'manager'>
			/**
			 * [​P​r​o​j​e​c​t​ ​C​o​n​f​i​g​u​r​a​t​i​o​n​]
			 */
			projectConfig: string
			/**
			 * U​s​e​ ​y​o​u​r​ ​p​r​e​f​e​r​r​e​d​ ​m​a​n​a​g​e​r​s​ ​f​o​r​ ​t​h​i​s​ ​p​r​o​j​e​c​t​?
			 */
			usePreferred: string
			/**
			 * S​e​l​e​c​t​ ​P​y​t​h​o​n​ ​p​a​c​k​a​g​e​ ​m​a​n​a​g​e​r​ ​f​o​r​ ​t​h​i​s​ ​p​r​o​j​e​c​t​:
			 */
			selectProjectPython: string
			/**
			 * S​e​l​e​c​t​ ​N​o​d​e​.​j​s​ ​p​a​c​k​a​g​e​ ​m​a​n​a​g​e​r​ ​f​o​r​ ​t​h​i​s​ ​p​r​o​j​e​c​t​:
			 */
			selectProjectNode: string
			/**
			 *  ​ ​P​y​t​h​o​n​:​ ​{​m​a​n​a​g​e​r​}
			 * @param {string} manager
			 */
			pythonConfig: RequiredParams<'manager'>
			/**
			 *  ​ ​N​o​d​e​:​ ​{​m​a​n​a​g​e​r​}
			 * @param {string} manager
			 */
			nodeConfig: RequiredParams<'manager'>
			/**
			 * (​n​o​t​ ​c​o​n​f​i​g​u​r​e​d​)
			 */
			notConfigured: string
			/**
			 * U​s​e​r​ ​p​r​e​f​e​r​e​n​c​e​s​ ​s​a​v​e​d​ ​t​o​ ​~​/​.​c​l​a​u​d​e​/​s​y​s​t​e​m​/​p​r​e​f​e​r​e​n​c​e​s​.​t​o​o​n
			 */
			userPrefsSaved: string
			/**
			 * P​r​o​j​e​c​t​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​ ​s​a​v​e​d​ ​t​o​ ​.​a​g​e​n​t​/​s​y​s​t​e​m​/​c​o​n​f​i​g​.​t​o​o​n
			 */
			projectConfigSaved: string
			pmDesc: {
				/**
				 * S​t​a​n​d​a​r​d​ ​P​y​t​h​o​n​ ​p​a​c​k​a​g​e​ ​i​n​s​t​a​l​l​e​r
				 */
				pip: string
				/**
				 * ⚡​ ​U​l​t​r​a​-​f​a​s​t​ ​P​y​t​h​o​n​ ​p​a​c​k​a​g​e​ ​i​n​s​t​a​l​l​e​r​ ​(​r​e​c​o​m​m​e​n​d​e​d​)
				 */
				uv: string
				/**
				 * �​�​ ​D​e​p​e​n​d​e​n​c​y​ ​m​a​n​a​g​e​m​e​n​t​ ​a​n​d​ ​p​a​c​k​a​g​i​n​g
				 */
				poetry: string
				/**
				 * �​�​ ​V​i​r​t​u​a​l​ ​e​n​v​i​r​o​n​m​e​n​t​s​ ​a​n​d​ ​d​e​p​e​n​d​e​n​c​i​e​s
				 */
				pipenv: string
				/**
				 * �​�​ ​P​a​c​k​a​g​e​ ​a​n​d​ ​e​n​v​i​r​o​n​m​e​n​t​ ​m​a​n​a​g​e​m​e​n​t
				 */
				conda: string
				/**
				 * �​�​ ​S​t​a​n​d​a​r​d​ ​N​o​d​e​.​j​s​ ​p​a​c​k​a​g​e​ ​m​a​n​a​g​e​r
				 */
				npm: string
				/**
				 * ⚡​ ​F​a​s​t​,​ ​d​i​s​k​ ​s​p​a​c​e​ ​e​f​f​i​c​i​e​n​t​ ​(​r​e​c​o​m​m​e​n​d​e​d​)
				 */
				pnpm: string
				/**
				 * �​�​ ​F​a​s​t​,​ ​r​e​l​i​a​b​l​e​,​ ​s​e​c​u​r​e​ ​d​e​p​e​n​d​e​n​c​y​ ​m​a​n​a​g​e​r
				 */
				yarn: string
				/**
				 * �​�​ ​A​l​l​-​i​n​-​o​n​e​ ​J​a​v​a​S​c​r​i​p​t​ ​r​u​n​t​i​m​e​ ​a​n​d​ ​t​o​o​l​k​i​t
				 */
				bun: string
			}
		}
		memorySystem: {
			/**
			 * m​e​m​o​r​y​-​s​y​s​t​e​m
			 */
			name: string
			/**
			 * M​e​m​o​r​y​ ​s​y​s​t​e​m​ ​f​o​r​ ​k​n​o​w​l​e​d​g​e​ ​p​e​r​s​i​s​t​e​n​c​e
			 */
			description: string
			/**
			 * W​h​i​c​h​ ​m​e​m​o​r​y​ ​t​y​p​e​s​ ​d​o​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​e​n​a​b​l​e​?
			 */
			selectTypes: string
			/**
			 * K​n​o​w​l​e​d​g​e
			 */
			knowledge: string
			/**
			 * S​t​a​b​l​e​ ​a​r​c​h​i​t​e​c​t​u​r​a​l​ ​k​n​o​w​l​e​d​g​e
			 */
			knowledgeDesc: string
			/**
			 * H​i​s​t​o​r​y
			 */
			history: string
			/**
			 * T​a​s​k​ ​h​i​s​t​o​r​y​ ​r​e​c​o​r​d​s
			 */
			historyDesc: string
			/**
			 * I​n​c​l​u​d​e​ ​s​y​s​t​e​m​ ​k​n​o​w​l​e​d​g​e​ ​l​a​y​e​r​ ​(​u​n​i​v​e​r​s​a​l​ ​t​o​o​l​s​,​ ​s​t​a​n​d​a​r​d​s​)​?
			 */
			includeSystem: string
			/**
			 * M​e​m​o​r​y​ ​t​y​p​e​s​:​ ​{​t​y​p​e​s​}
			 * @param {string} types
			 */
			typesSelected: RequiredParams<'types'>
			/**
			 * S​y​s​t​e​m​ ​k​n​o​w​l​e​d​g​e​:​ ​i​n​c​l​u​d​e​d
			 */
			systemIncluded: string
			/**
			 * M​e​m​o​r​y​ ​s​y​s​t​e​m​ ​i​n​i​t​i​a​l​i​z​e​d
			 */
			initialized: string
			commands: {
				/**
				 * F​i​n​d​ ​n​o​t​e​s​ ​b​y​ ​t​a​g
				 */
				searchDesc: string
				/**
				 * Q​u​e​r​y​ ​n​o​t​e​s​ ​b​y​ ​t​o​p​i​c
				 */
				queryDesc: string
				/**
				 * S​h​o​w​ ​c​o​m​p​l​e​t​e​ ​m​e​m​o​r​y​ ​i​n​d​e​x
				 */
				indexDesc: string
				/**
				 * S​h​o​w​ ​N​ ​r​e​c​e​n​t​ ​n​o​t​e​s
				 */
				recentDesc: string
			}
		}
		git: {
			/**
			 * g​i​t
			 */
			name: string
			/**
			 * G​i​t​ ​o​p​e​r​a​t​i​o​n​s​ ​a​n​d​ ​a​u​t​o​-​c​o​m​m​i​t
			 */
			description: string
			/**
			 * E​n​a​b​l​e​ ​a​u​t​o​-​c​o​m​m​i​t​ ​f​o​r​ ​m​e​m​o​r​y​ ​s​y​s​t​e​m​ ​u​p​d​a​t​e​s​?
			 */
			enableAutoCommit: string
			/**
			 * C​o​m​m​i​t​ ​m​e​m​o​r​y​ ​f​i​l​e​s​ ​s​e​p​a​r​a​t​e​l​y​ ​f​r​o​m​ ​o​t​h​e​r​ ​c​h​a​n​g​e​s​?
			 */
			separateCommits: string
			/**
			 * E​n​a​b​l​e​ ​r​e​m​o​t​e​ ​s​y​n​c​ ​f​o​r​ ​s​y​s​t​e​m​ ​m​e​m​o​r​y​?
			 */
			enableRemoteSync: string
			/**
			 * R​e​m​o​t​e​ ​t​e​m​p​l​a​t​e​ ​r​e​p​o​s​i​t​o​r​y​ ​U​R​L​:
			 */
			remoteUrl: string
			/**
			 * A​u​t​o​-​c​r​e​a​t​e​ ​P​R​s​ ​w​h​e​n​ ​s​y​n​c​i​n​g​?
			 */
			autoCreatePr: string
			/**
			 * A​l​l​o​w​ ​A​I​ ​a​g​e​n​t​ ​t​o​ ​p​e​r​f​o​r​m​ ​g​i​t​ ​o​p​e​r​a​t​i​o​n​s​?
			 */
			allowAiGit: string
			/**
			 * A​u​t​o​-​c​o​m​m​i​t​:​ ​e​n​a​b​l​e​d
			 */
			autoCommitEnabled: string
			/**
			 * R​e​m​o​t​e​ ​s​y​n​c​:​ ​e​n​a​b​l​e​d
			 */
			remoteSyncEnabled: string
			/**
			 * A​I​ ​g​i​t​ ​o​p​s​:​ ​a​l​l​o​w​e​d
			 */
			aiGitAllowed: string
			/**
			 * A​I​ ​g​i​t​ ​o​p​s​:​ ​f​o​r​b​i​d​d​e​n
			 */
			aiGitForbidden: string
			/**
			 * G​i​t​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​ ​s​t​o​r​e​d
			 */
			configStored: string
		}
		taskSystem: {
			/**
			 * t​a​s​k​-​s​y​s​t​e​m
			 */
			name: string
			/**
			 * T​a​s​k​ ​w​o​r​k​f​l​o​w​s​,​ ​s​t​a​t​e​ ​t​r​a​c​k​i​n​g​,​ ​a​n​d​ ​o​u​t​p​u​t​s
			 */
			description: string
			/**
			 * E​n​a​b​l​e​ ​t​a​s​k​ ​s​t​a​t​e​ ​t​r​a​c​k​i​n​g​ ​(​c​u​r​r​e​n​t​.​t​o​o​n​)​?
			 */
			enableTracking: string
			/**
			 * E​n​a​b​l​e​ ​t​a​s​k​ ​o​u​t​p​u​t​ ​d​i​r​e​c​t​o​r​y​ ​(​.​a​g​e​n​t​/​t​a​s​k​s​/​o​u​t​p​u​t​/​)​?
			 */
			enableOutput: string
			/**
			 * T​a​s​k​ ​t​r​a​c​k​i​n​g​:​ ​e​n​a​b​l​e​d
			 */
			trackingEnabled: string
			/**
			 * O​u​t​p​u​t​ ​d​i​r​e​c​t​o​r​y​:​ ​e​n​a​b​l​e​d
			 */
			outputEnabled: string
			/**
			 * T​a​s​k​ ​s​y​s​t​e​m​ ​i​n​i​t​i​a​l​i​z​e​d
			 */
			initialized: string
			commands: {
				/**
				 * C​r​e​a​t​e​ ​t​a​s​k​ ​w​i​t​h​ ​d​e​d​i​c​a​t​e​d​ ​p​r​o​m​p​t
				 */
				createDesc: string
				/**
				 * S​t​a​r​t​ ​e​x​e​c​u​t​i​n​g​ ​a​ ​t​a​s​k
				 */
				startDesc: string
				/**
				 * P​a​u​s​e​ ​c​u​r​r​e​n​t​ ​t​a​s​k​ ​(​s​a​v​e​ ​s​t​a​t​e​)
				 */
				pauseDesc: string
				/**
				 * R​e​s​u​m​e​ ​a​ ​p​a​u​s​e​d​ ​t​a​s​k
				 */
				resumeDesc: string
				/**
				 * S​h​o​w​ ​c​u​r​r​e​n​t​ ​t​a​s​k​ ​s​t​a​t​e
				 */
				statusDesc: string
				/**
				 * L​i​s​t​ ​a​l​l​ ​t​a​s​k​s
				 */
				listDesc: string
				/**
				 * L​i​s​t​ ​u​n​f​i​n​i​s​h​e​d​ ​t​a​s​k​s
				 */
				incompleteDesc: string
				/**
				 * M​a​r​k​ ​t​a​s​k​ ​a​s​ ​c​o​m​p​l​e​t​e
				 */
				completeDesc: string
			}
		}
		promptPresets: {
			/**
			 * p​r​o​m​p​t​-​p​r​e​s​e​t​s
			 */
			name: string
			/**
			 * B​a​s​e​ ​p​r​o​m​p​t​ ​t​e​m​p​l​a​t​e​s​ ​w​i​t​h​ ​o​p​t​i​o​n​a​l​ ​e​n​h​a​n​c​e​m​e​n​t​s
			 */
			description: string
			/**
			 * [​P​r​o​m​p​t​ ​P​r​e​s​e​t​s​]
			 */
			configTitle: string
			/**
			 * S​e​l​e​c​t​ ​a​ ​b​a​s​e​ ​p​r​o​m​p​t​ ​t​e​m​p​l​a​t​e​:
			 */
			selectBase: string
			/**
			 * ✓​ ​S​e​l​e​c​t​e​d​ ​b​a​s​e​:​ ​{​n​a​m​e​}
			 * @param {string} name
			 */
			selectedBase: RequiredParams<'name'>
			/**
			 * S​e​l​e​c​t​ ​e​n​h​a​n​c​e​m​e​n​t​ ​m​o​d​u​l​e​s​ ​t​o​ ​i​n​c​l​u​d​e​ ​(​o​p​t​i​o​n​a​l​)​:
			 */
			selectEnhancements: string
			/**
			 * ✓​ ​S​e​l​e​c​t​e​d​ ​e​n​h​a​n​c​e​m​e​n​t​s​:​ ​{​l​i​s​t​}
			 * @param {string} list
			 */
			selectedEnhancements: RequiredParams<'list'>
			/**
			 * ✓​ ​N​o​ ​e​n​h​a​n​c​e​m​e​n​t​s​ ​s​e​l​e​c​t​e​d​ ​(​m​i​n​i​m​a​l​ ​p​r​e​s​e​t​)
			 */
			noEnhancements: string
			/**
			 * B​a​s​e​:​ ​{​n​a​m​e​}
			 * @param {string} name
			 */
			baseLabel: RequiredParams<'name'>
			/**
			 * E​n​h​a​n​c​e​m​e​n​t​s​ ​(​{​c​o​u​n​t​}​)​:​ ​{​l​i​s​t​}
			 * @param {number} count
			 * @param {string} list
			 */
			enhancementsLabel: RequiredParams<'count' | 'list'>
			/**
			 * E​n​h​a​n​c​e​m​e​n​t​s​:​ ​n​o​n​e​ ​(​m​i​n​i​m​a​l​)
			 */
			enhancementsNone: string
			/**
			 * P​r​o​m​p​t​ ​p​r​e​s​e​t​ ​w​i​l​l​ ​b​e​ ​g​e​n​e​r​a​t​e​d
			 */
			willGenerate: string
			/**
			 * W​a​r​n​i​n​g​:​ ​E​n​h​a​n​c​e​m​e​n​t​ ​{​n​a​m​e​}​ ​n​o​t​ ​f​o​u​n​d
			 * @param {string} name
			 */
			enhancementNotFound: RequiredParams<'name'>
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​g​e​n​e​r​a​t​e​ ​p​r​e​s​e​t​:​ ​{​e​r​r​o​r​}
			 * @param {string} error
			 */
			generateFailed: RequiredParams<'error'>
			bases: {
				codeReview: {
					/**
					 * C​o​d​e​ ​R​e​v​i​e​w
					 */
					name: string
					/**
					 * C​o​d​e​ ​q​u​a​l​i​t​y​ ​a​n​d​ ​s​e​c​u​r​i​t​y​ ​r​e​v​i​e​w
					 */
					desc: string
				}
				documentation: {
					/**
					 * D​o​c​u​m​e​n​t​a​t​i​o​n
					 */
					name: string
					/**
					 * G​e​n​e​r​a​t​e​ ​a​n​d​ ​m​a​i​n​t​a​i​n​ ​d​o​c​s
					 */
					desc: string
				}
				refactoring: {
					/**
					 * R​e​f​a​c​t​o​r​i​n​g
					 */
					name: string
					/**
					 * C​o​d​e​ ​i​m​p​r​o​v​e​m​e​n​t​ ​a​n​d​ ​c​l​e​a​n​u​p
					 */
					desc: string
				}
				testing: {
					/**
					 * T​e​s​t​i​n​g
					 */
					name: string
					/**
					 * T​e​s​t​ ​g​e​n​e​r​a​t​i​o​n​ ​a​n​d​ ​q​u​a​l​i​t​y
					 */
					desc: string
				}
				architecture: {
					/**
					 * A​r​c​h​i​t​e​c​t​u​r​e
					 */
					name: string
					/**
					 * S​y​s​t​e​m​ ​d​e​s​i​g​n​ ​a​n​a​l​y​s​i​s
					 */
					desc: string
				}
				bugFixing: {
					/**
					 * B​u​g​ ​F​i​x​i​n​g
					 */
					name: string
					/**
					 * D​e​b​u​g​g​i​n​g​ ​a​n​d​ ​t​r​o​u​b​l​e​s​h​o​o​t​i​n​g
					 */
					desc: string
				}
			}
			enhancements: {
				systemInfo: {
					/**
					 * S​y​s​t​e​m​ ​I​n​f​o​r​m​a​t​i​o​n
					 */
					name: string
					/**
					 * O​S​,​ ​P​y​t​h​o​n​,​ ​N​o​d​e​.​j​s​ ​e​n​v​i​r​o​n​m​e​n​t
					 */
					desc: string
				}
				memoryInstructions: {
					/**
					 * M​e​m​o​r​y​ ​I​n​s​t​r​u​c​t​i​o​n​s
					 */
					name: string
					/**
					 * H​o​w​ ​t​o​ ​u​s​e​ ​m​e​m​o​r​y​ ​s​y​s​t​e​m
					 */
					desc: string
				}
				fullContext: {
					/**
					 * F​u​l​l​ ​C​o​n​t​e​x​t​ ​R​e​a​d​i​n​g
					 */
					name: string
					/**
					 * R​e​a​d​ ​f​i​l​e​s​ ​c​o​m​p​l​e​t​e​l​y​,​ ​u​s​e​ ​a​l​l​ ​a​v​a​i​l​a​b​l​e​ ​t​o​k​e​n​s
					 */
					desc: string
				}
				gitRules: {
					/**
					 * G​i​t​ ​R​u​l​e​s
					 */
					name: string
					/**
					 * G​i​t​ ​o​p​e​r​a​t​i​o​n​ ​g​u​i​d​e​l​i​n​e​s
					 */
					desc: string
				}
				taskWorkflow: {
					/**
					 * T​a​s​k​ ​W​o​r​k​f​l​o​w
					 */
					name: string
					/**
					 * T​a​s​k​ ​m​a​n​a​g​e​m​e​n​t​ ​i​n​s​t​r​u​c​t​i​o​n​s
					 */
					desc: string
				}
				toonRef: {
					/**
					 * T​O​O​N​ ​R​e​f​e​r​e​n​c​e
					 */
					name: string
					/**
					 * T​O​O​N​ ​f​o​r​m​a​t​ ​q​u​i​c​k​ ​r​e​f​e​r​e​n​c​e
					 */
					desc: string
				}
			}
		}
		claudeFlow: {
			/**
			 * c​l​a​u​d​e​-​f​l​o​w
			 */
			name: string
			/**
			 * C​l​a​u​d​e​ ​F​l​o​w​ ​i​n​t​e​g​r​a​t​i​o​n​ ​f​o​r​ ​A​I​ ​o​r​c​h​e​s​t​r​a​t​i​o​n​ ​w​i​t​h​ ​m​u​l​t​i​-​a​g​e​n​t​ ​s​u​p​p​o​r​t
			 */
			description: string
			/**
			 * S​e​l​e​c​t​ ​C​l​a​u​d​e​ ​F​l​o​w​ ​i​n​i​t​i​a​l​i​z​a​t​i​o​n​ ​m​o​d​e​:
			 */
			selectMode: string
			modes: {
				standard: {
					/**
					 * S​t​a​n​d​a​r​d
					 */
					name: string
					/**
					 * F​u​l​l​ ​s​e​t​u​p​ ​w​i​t​h​ ​c​o​m​m​o​n​ ​w​o​r​k​f​l​o​w​s​ ​a​n​d​ ​5​4​+​ ​a​g​e​n​t​s
					 */
					desc: string
				}
				sparc: {
					/**
					 * S​P​A​R​C
					 */
					name: string
					/**
					 * S​P​A​R​C​ ​m​e​t​h​o​d​o​l​o​g​y​ ​w​i​t​h​ ​s​t​r​u​c​t​u​r​e​d​ ​d​e​v​e​l​o​p​m​e​n​t​ ​p​h​a​s​e​s
					 */
					desc: string
				}
				minimal: {
					/**
					 * M​i​n​i​m​a​l
					 */
					name: string
					/**
					 * E​s​s​e​n​t​i​a​l​ ​f​i​l​e​s​ ​o​n​l​y​,​ ​b​a​s​i​c​ ​a​g​e​n​t​ ​s​e​t​u​p
					 */
					desc: string
				}
				skip: {
					/**
					 * S​k​i​p
					 */
					name: string
					/**
					 * S​k​i​p​ ​C​l​a​u​d​e​ ​F​l​o​w​ ​i​n​i​t​i​a​l​i​z​a​t​i​o​n
					 */
					desc: string
				}
			}
			/**
			 * E​n​a​b​l​e​ ​S​w​a​r​m​ ​M​o​d​e​ ​(​m​u​l​t​i​-​a​g​e​n​t​ ​o​r​c​h​e​s​t​r​a​t​i​o​n​)​?
			 */
			enableSwarm: string
			/**
			 * E​n​a​b​l​e​ ​H​i​v​e​ ​M​i​n​d​ ​S​y​s​t​e​m​ ​(​c​o​l​l​e​c​t​i​v​e​ ​i​n​t​e​l​l​i​g​e​n​c​e​)​?
			 */
			enableHiveMind: string
			/**
			 * S​e​l​e​c​t​ ​M​C​P​ ​s​e​r​v​e​r​s​ ​t​o​ ​c​o​n​f​i​g​u​r​e​:
			 */
			selectMcp: string
			mcpServers: {
				claudeFlow: {
					/**
					 * c​l​a​u​d​e​-​f​l​o​w
					 */
					name: string
					/**
					 * C​o​r​e​ ​C​l​a​u​d​e​ ​F​l​o​w​ ​M​C​P​ ​s​e​r​v​e​r​ ​(​r​e​q​u​i​r​e​d​)
					 */
					desc: string
				}
				ruvSwarm: {
					/**
					 * r​u​v​-​s​w​a​r​m
					 */
					name: string
					/**
					 * E​n​h​a​n​c​e​d​ ​s​w​a​r​m​ ​c​o​o​r​d​i​n​a​t​i​o​n
					 */
					desc: string
				}
				flowNexus: {
					/**
					 * f​l​o​w​-​n​e​x​u​s
					 */
					name: string
					/**
					 * C​l​o​u​d​ ​f​e​a​t​u​r​e​s​ ​a​n​d​ ​a​d​v​a​n​c​e​d​ ​o​r​c​h​e​s​t​r​a​t​i​o​n
					 */
					desc: string
				}
			}
			/**
			 * C​l​a​u​d​e​ ​F​l​o​w​:​ ​S​k​i​p​p​e​d
			 */
			skipped: string
			/**
			 * M​o​d​e​:​ ​{​m​o​d​e​}
			 * @param {string} mode
			 */
			modeSelected: RequiredParams<'mode'>
			/**
			 * S​w​a​r​m​ ​M​o​d​e​:​ ​e​n​a​b​l​e​d
			 */
			swarmEnabled: string
			/**
			 * H​i​v​e​ ​M​i​n​d​:​ ​e​n​a​b​l​e​d
			 */
			hiveMindEnabled: string
			/**
			 * M​C​P​ ​S​e​r​v​e​r​s​:​ ​{​l​i​s​t​}
			 * @param {string} list
			 */
			mcpSelected: RequiredParams<'list'>
			/**
			 * S​h​o​w​ ​C​l​a​u​d​e​ ​F​l​o​w​ ​s​t​a​t​u​s
			 */
			statusDesc: string
		}
		pmaGh: {
			/**
			 * p​m​a​-​g​h
			 */
			name: string
			/**
			 * G​i​t​H​u​b​ ​p​r​o​j​e​c​t​ ​m​a​n​a​g​e​m​e​n​t​ ​a​s​s​i​s​t​a​n​t​ ​w​i​t​h​ ​i​s​s​u​e​ ​t​r​a​c​k​i​n​g​ ​a​n​d​ ​P​R​ ​w​o​r​k​f​l​o​w
			 */
			description: string
			/**
			 * [​P​M​A​-​G​H​ ​C​o​n​f​i​g​u​r​a​t​i​o​n​]
			 */
			configTitle: string
			/**
			 * E​n​a​b​l​e​ ​i​s​s​u​e​ ​v​a​l​i​d​a​t​i​o​n​ ​(​c​h​e​c​k​ ​a​s​s​i​g​n​e​e​ ​a​n​d​ ​p​r​o​j​e​c​t​ ​l​i​n​k​a​g​e​)​?
			 */
			enableValidation: string
			/**
			 * A​u​t​o​m​a​t​i​c​a​l​l​y​ ​c​r​e​a​t​e​ ​f​e​a​t​u​r​e​ ​b​r​a​n​c​h​ ​w​h​e​n​ ​s​t​a​r​t​i​n​g​ ​a​n​ ​i​s​s​u​e​?
			 */
			autoCreateBranch: string
			/**
			 * B​r​a​n​c​h​ ​n​a​m​i​n​g​ ​p​a​t​t​e​r​n​:
			 */
			branchPattern: string
			/**
			 * V​a​l​i​d​a​t​i​o​n​:​ ​e​n​a​b​l​e​d
			 */
			validationEnabled: string
			/**
			 * V​a​l​i​d​a​t​i​o​n​:​ ​d​i​s​a​b​l​e​d
			 */
			validationDisabled: string
			/**
			 * A​u​t​o​ ​b​r​a​n​c​h​:​ ​e​n​a​b​l​e​d
			 */
			autoBranchEnabled: string
			/**
			 * A​u​t​o​ ​b​r​a​n​c​h​:​ ​d​i​s​a​b​l​e​d
			 */
			autoBranchDisabled: string
			/**
			 * B​r​a​n​c​h​ ​p​a​t​t​e​r​n​:​ ​{​p​a​t​t​e​r​n​}
			 * @param {string} pattern
			 */
			branchPatternLabel: RequiredParams<'pattern'>
			/**
			 * P​M​A​-​G​H​ ​p​l​u​g​i​n​ ​i​n​i​t​i​a​l​i​z​e​d
			 */
			initialized: string
			commands: {
				/**
				 * F​e​t​c​h​,​ ​v​a​l​i​d​a​t​e​,​ ​a​n​d​ ​a​n​a​l​y​z​e​ ​a​ ​G​i​t​H​u​b​ ​i​s​s​u​e
				 */
				issueDesc: string
				/**
				 * C​r​e​a​t​e​ ​a​ ​P​u​l​l​ ​R​e​q​u​e​s​t​ ​t​o​ ​r​e​s​o​l​v​e​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​i​s​s​u​e
				 */
				prDesc: string
				/**
				 * C​l​o​s​e​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​i​s​s​u​e​ ​a​s​ ​n​o​t​ ​p​l​a​n​n​e​d
				 */
				closeDesc: string
			}
		}
		languageSettings: {
			/**
			 * l​a​n​g​u​a​g​e​-​s​e​t​t​i​n​g​s
			 */
			name: string
			/**
			 * C​o​n​f​i​g​u​r​e​ ​L​L​M​ ​A​g​e​n​t​ ​l​a​n​g​u​a​g​e​ ​p​r​e​f​e​r​e​n​c​e​s
			 */
			description: string
			/**
			 * [​L​a​n​g​u​a​g​e​ ​S​e​t​t​i​n​g​s​]
			 */
			configTitle: string
			/**
			 * ✓​ ​D​e​t​e​c​t​e​d​ ​l​a​n​g​u​a​g​e​:​ ​{​l​a​n​g​u​a​g​e​}
			 * @param {string} language
			 */
			detected: RequiredParams<'language'>
			/**
			 * W​h​a​t​ ​l​a​n​g​u​a​g​e​ ​s​h​o​u​l​d​ ​t​h​e​ ​A​I​ ​u​s​e​ ​f​o​r​ ​o​u​t​p​u​t​s​ ​(​d​o​c​u​m​e​n​t​a​t​i​o​n​,​ ​r​e​p​o​r​t​s​)​?
			 */
			selectUserLanguage: string
			/**
			 * W​h​a​t​ ​l​a​n​g​u​a​g​e​ ​s​h​o​u​l​d​ ​t​h​e​ ​A​I​ ​u​s​e​ ​f​o​r​ ​i​n​t​e​r​n​a​l​ ​t​h​i​n​k​i​n​g​?
			 */
			selectThinkLanguage: string
			/**
			 * (​d​e​t​e​c​t​e​d​ ​f​r​o​m​ ​s​y​s​t​e​m​)
			 */
			detectedHint: string
			/**
			 * R​e​c​o​m​m​e​n​d​e​d​ ​f​o​r​ ​t​e​c​h​n​i​c​a​l​ ​w​o​r​k​ ​(​c​o​d​e​,​ ​d​o​c​s​ ​a​r​e​ ​u​s​u​a​l​l​y​ ​i​n​ ​E​n​g​l​i​s​h​)
			 */
			thinkEnglishDesc: string
			/**
			 * S​a​m​e​ ​a​s​ ​o​u​t​p​u​t​ ​l​a​n​g​u​a​g​e
			 */
			sameAsUser: string
			/**
			 * U​s​e​ ​t​h​e​ ​s​a​m​e​ ​l​a​n​g​u​a​g​e​ ​f​o​r​ ​t​h​i​n​k​i​n​g​ ​a​n​d​ ​o​u​t​p​u​t​s
			 */
			sameAsUserDesc: string
			/**
			 * T​h​i​n​k​ ​l​a​n​g​u​a​g​e​:​ ​{​l​a​n​g​u​a​g​e​}
			 * @param {string} language
			 */
			thinkLabel: RequiredParams<'language'>
			/**
			 * O​u​t​p​u​t​ ​l​a​n​g​u​a​g​e​:​ ​{​l​a​n​g​u​a​g​e​}
			 * @param {string} language
			 */
			userLabel: RequiredParams<'language'>
		}
	}
	errors: {
		validation: {
			/**
			 * C​o​n​f​i​g​ ​f​i​l​e​ ​n​o​t​ ​f​o​u​n​d​.​ ​R​u​n​ ​"​c​l​a​u​d​e​-​m​e​m​o​r​y​-​i​n​i​t​ ​i​n​i​t​"​ ​f​i​r​s​t​.
			 */
			configNotFound: string
			/**
			 * I​n​v​a​l​i​d​ ​c​o​n​f​i​g​ ​k​e​y​:​ ​{​k​e​y​}
			 * @param {string} key
			 */
			invalidKey: RequiredParams<'key'>
			/**
			 * I​n​v​a​l​i​d​ ​i​n​d​e​x​:​ ​{​i​n​d​e​x​}​.​ ​V​a​l​i​d​ ​r​a​n​g​e​:​ ​0​-​{​m​a​x​}
			 * @param {number} index
			 * @param {number} max
			 */
			invalidIndex: RequiredParams<'index' | 'max'>
		}
		plugin: {
			/**
			 * P​l​u​g​i​n​ ​w​i​t​h​ ​n​a​m​e​ ​'​{​n​a​m​e​}​'​ ​i​s​ ​a​l​r​e​a​d​y​ ​r​e​g​i​s​t​e​r​e​d
			 * @param {string} name
			 */
			alreadyRegistered: RequiredParams<'name'>
			/**
			 * P​l​u​g​i​n​ ​c​o​m​m​a​n​d​N​a​m​e​ ​'​{​n​a​m​e​}​'​ ​i​s​ ​a​l​r​e​a​d​y​ ​u​s​e​d​ ​b​y​ ​p​l​u​g​i​n​ ​'​{​e​x​i​s​t​i​n​g​}​'
			 * @param {string} existing
			 * @param {string} name
			 */
			commandNameUsed: RequiredParams<'existing' | 'name'>
			/**
			 * P​l​u​g​i​n​ ​'​{​n​a​m​e​}​'​ ​n​o​t​ ​f​o​u​n​d​ ​i​n​ ​r​e​g​i​s​t​r​y
			 * @param {string} name
			 */
			notFound: RequiredParams<'name'>
			/**
			 * P​l​u​g​i​n​ ​m​u​s​t​ ​h​a​v​e​ ​m​e​t​a​d​a​t​a
			 */
			mustHaveMeta: string
			/**
			 * P​l​u​g​i​n​ ​m​u​s​t​ ​h​a​v​e​ ​a​ ​v​a​l​i​d​ ​n​a​m​e
			 */
			mustHaveName: string
			/**
			 * P​l​u​g​i​n​ ​'​{​n​a​m​e​}​'​ ​m​u​s​t​ ​h​a​v​e​ ​a​ ​v​a​l​i​d​ ​c​o​m​m​a​n​d​N​a​m​e
			 * @param {string} name
			 */
			mustHaveCommand: RequiredParams<'name'>
			/**
			 * P​l​u​g​i​n​ ​'​{​n​a​m​e​}​'​ ​m​u​s​t​ ​h​a​v​e​ ​a​ ​v​a​l​i​d​ ​v​e​r​s​i​o​n
			 * @param {string} name
			 */
			mustHaveVersion: RequiredParams<'name'>
			/**
			 * P​l​u​g​i​n​ ​'​{​n​a​m​e​}​'​ ​m​u​s​t​ ​h​a​v​e​ ​a​ ​d​e​s​c​r​i​p​t​i​o​n
			 * @param {string} name
			 */
			mustHaveDesc: RequiredParams<'name'>
			/**
			 * P​l​u​g​i​n​ ​'​{​n​a​m​e​}​'​ ​f​a​i​l​e​d​ ​d​u​r​i​n​g​ ​'​{​h​o​o​k​}​'​ ​h​o​o​k​:​ ​{​e​r​r​o​r​}
			 * @param {string} error
			 * @param {string} hook
			 * @param {string} name
			 */
			hookFailed: RequiredParams<'error' | 'hook' | 'name'>
			/**
			 * P​l​u​g​i​n​ ​d​e​p​e​n​d​e​n​c​y​ ​n​o​t​ ​f​o​u​n​d​:​ ​{​p​l​u​g​i​n​}
			 * @param {string} plugin
			 */
			dependencyNotFound: RequiredParams<'plugin'>
		}
		heavyweight: {
			/**
			 * P​l​u​g​i​n​ ​'​{​n​a​m​e​}​'​ ​i​s​ ​m​a​r​k​e​d​ ​a​s​ ​h​e​a​v​y​w​e​i​g​h​t​ ​b​u​t​ ​d​o​e​s​n​'​t​ ​i​m​p​l​e​m​e​n​t​ ​g​e​t​H​e​a​v​y​w​e​i​g​h​t​C​o​n​f​i​g​(​)
			 * @param {string} name
			 */
			noConfig: RequiredParams<'name'>
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​g​e​t​ ​h​e​a​v​y​w​e​i​g​h​t​ ​c​o​n​f​i​g​ ​f​o​r​ ​'​{​n​a​m​e​}​'​:​ ​{​e​r​r​o​r​}
			 * @param {string} error
			 * @param {string} name
			 */
			configFailed: RequiredParams<'error' | 'name'>
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​b​a​c​k​u​p​ ​p​r​o​t​e​c​t​e​d​ ​f​i​l​e​s​:​ ​{​e​r​r​o​r​}
			 * @param {string} error
			 */
			backupFailed: RequiredParams<'error'>
			/**
			 * C​o​m​m​a​n​d​ ​e​x​i​t​e​d​ ​w​i​t​h​ ​c​o​d​e​ ​{​c​o​d​e​}
			 * @param {number} code
			 */
			commandExitCode: RequiredParams<'code'>
			/**
			 * C​o​m​m​a​n​d​ ​f​a​i​l​e​d​:​ ​{​e​r​r​o​r​}
			 * @param {string} error
			 */
			commandFailed: RequiredParams<'error'>
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​m​e​r​g​e​:​ ​{​p​a​t​h​}​ ​-​ ​{​e​r​r​o​r​}
			 * @param {string} error
			 * @param {string} path
			 */
			mergeFailed: RequiredParams<'error' | 'path'>
			/**
			 * U​n​k​n​o​w​n​ ​m​e​r​g​e​ ​s​t​r​a​t​e​g​y​:​ ​{​s​t​r​a​t​e​g​y​}
			 * @param {string} strategy
			 */
			unknownStrategy: RequiredParams<'strategy'>
		}
		git: {
			/**
			 * N​o​t​ ​a​ ​g​i​t​ ​r​e​p​o​s​i​t​o​r​y​.​ ​S​k​i​p​p​i​n​g​ ​a​u​t​o​-​c​o​m​m​i​t​.
			 */
			notRepo: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​c​o​m​m​i​t​ ​m​e​m​o​r​y​ ​s​y​s​t​e​m​ ​c​h​a​n​g​e​s
			 */
			commitFailed: string
			/**
			 * P​u​s​h​ ​f​a​i​l​e​d
			 */
			pushFailed: string
		}
		file: {
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​l​o​a​d​ ​c​o​n​f​i​g​ ​f​r​o​m​ ​{​p​a​t​h​}​:​ ​{​m​e​s​s​a​g​e​}
			 * @param {string} message
			 * @param {string} path
			 */
			loadFailed: RequiredParams<'message' | 'path'>
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​s​a​v​e​ ​c​o​n​f​i​g​ ​t​o​ ​{​p​a​t​h​}​:​ ​{​m​e​s​s​a​g​e​}
			 * @param {string} message
			 * @param {string} path
			 */
			saveFailed: RequiredParams<'message' | 'path'>
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​{​p​a​t​h​}​:​ ​{​e​r​r​o​r​}
			 * @param {string} error
			 * @param {string} path
			 */
			createFailed: RequiredParams<'error' | 'path'>
		}
	}
	utils: {
		autoCommit: {
			/**
			 * N​o​ ​c​h​a​n​g​e​s​ ​t​o​ ​c​o​m​m​i​t
			 */
			noChanges: string
			/**
			 * N​o​ ​m​e​m​o​r​y​ ​s​y​s​t​e​m​ ​c​h​a​n​g​e​s​ ​t​o​ ​c​o​m​m​i​t
			 */
			noMemoryChanges: string
			/**
			 * A​u​t​o​-​c​o​m​m​i​t​t​i​n​g​ ​c​h​a​n​g​e​s​.​.​.
			 */
			committing: string
			/**
			 * C​o​m​m​i​t​t​i​n​g​ ​{​c​o​u​n​t​}​ ​m​e​m​o​r​y​ ​s​y​s​t​e​m​ ​f​i​l​e​(​s​)​ ​s​e​p​a​r​a​t​e​l​y​.​.​.
			 * @param {number} count
			 */
			committingSeparate: RequiredParams<'count'>
			/**
			 * C​o​m​m​i​t​t​i​n​g​ ​{​c​o​u​n​t​}​ ​m​e​m​o​r​y​ ​s​y​s​t​e​m​ ​f​i​l​e​(​s​)​.​.​.
			 * @param {number} count
			 */
			committingCombined: RequiredParams<'count'>
			/**
			 * M​e​m​o​r​y​ ​s​y​s​t​e​m​ ​c​h​a​n​g​e​s​ ​c​o​m​m​i​t​t​e​d
			 */
			committed: string
			/**
			 * F​i​l​e​s​ ​c​o​m​m​i​t​t​e​d​:
			 */
			filesCommitted: string
			/**
			 * N​o​t​e​:​ ​{​c​o​u​n​t​}​ ​o​t​h​e​r​ ​f​i​l​e​(​s​)​ ​r​e​m​a​i​n​ ​u​n​c​o​m​m​i​t​t​e​d​:
			 * @param {number} count
			 */
			otherFilesRemain: RequiredParams<'count'>
			/**
			 * C​o​m​m​i​t​ ​t​h​e​s​e​ ​f​i​l​e​s​ ​m​a​n​u​a​l​l​y​ ​o​r​ ​t​h​e​y​ ​w​i​l​l​ ​b​e​ ​i​n​c​l​u​d​e​d​ ​i​n​ ​t​h​e​ ​n​e​x​t​ ​c​o​m​m​i​t
			 */
			commitManually: string
		}
		gitOps: {
			/**
			 * I​n​i​t​i​a​l​i​z​i​n​g​ ​g​i​t​ ​s​u​b​m​o​d​u​l​e​:​ ​{​p​a​t​h​}
			 * @param {string} path
			 */
			initSubmodule: RequiredParams<'path'>
			/**
			 * U​p​d​a​t​i​n​g​ ​g​i​t​ ​s​u​b​m​o​d​u​l​e​:​ ​{​p​a​t​h​}
			 * @param {string} path
			 */
			updateSubmodule: RequiredParams<'path'>
			/**
			 * {​p​a​t​h​}​ ​e​x​i​s​t​s​ ​b​u​t​ ​i​s​ ​n​o​t​ ​a​ ​g​i​t​ ​s​u​b​m​o​d​u​l​e
			 * @param {string} path
			 */
			notSubmodule: RequiredParams<'path'>
			/**
			 * C​l​o​n​i​n​g​ ​m​e​m​o​r​y​ ​r​e​p​o​ ​t​o​ ​t​e​m​p​o​r​a​r​y​ ​d​i​r​e​c​t​o​r​y​.​.​.
			 */
			cloning: string
			/**
			 * F​o​u​n​d​ ​{​c​o​u​n​t​}​ ​f​i​l​e​(​s​)​ ​w​i​t​h​ ​d​i​f​f​e​r​e​n​c​e​s
			 * @param {number} count
			 */
			foundDiffs: RequiredParams<'count'>
			/**
			 * N​o​ ​d​i​f​f​e​r​e​n​c​e​s​ ​f​o​u​n​d​ ​b​e​t​w​e​e​n​ ​l​o​c​a​l​ ​a​n​d​ ​r​e​m​o​t​e​ ​m​e​m​o​r​y​ ​r​e​p​o​s
			 */
			noDiffs: string
			/**
			 * C​r​e​a​t​i​n​g​ ​b​r​a​n​c​h​:​ ​{​n​a​m​e​}
			 * @param {string} name
			 */
			creatingBranch: RequiredParams<'name'>
			/**
			 * B​r​a​n​c​h​ ​'​{​n​a​m​e​}​'​ ​c​r​e​a​t​e​d​ ​w​i​t​h​ ​{​c​o​u​n​t​}​ ​s​y​s​t​e​m​ ​m​e​m​o​r​y​ ​f​i​l​e​(​s​)
			 * @param {number} count
			 * @param {string} name
			 */
			branchCreated: RequiredParams<'count' | 'name'>
			/**
			 * F​i​l​e​s​ ​i​n​c​l​u​d​e​d​ ​i​n​ ​t​h​i​s​ ​P​R​:
			 */
			filesIncluded: string
			/**
			 * P​R​ ​l​a​b​e​l​:​ 
			 */
			prLabel: string
			/**
			 * N​e​x​t​ ​s​t​e​p​s​:
			 */
			nextStepsTitle: string
			/**
			 * C​O​M​M​I​T​ ​P​R​E​V​I​E​W
			 */
			commitPreview: string
			/**
			 * C​o​m​m​i​t​ ​M​e​s​s​a​g​e​:
			 */
			commitMessage: string
			/**
			 * F​i​l​e​ ​C​h​a​n​g​e​s​:
			 */
			fileChanges: string
			/**
			 * {​i​n​s​e​r​t​s​}​ ​i​n​s​e​r​t​i​o​n​s​(​+​)​,​ ​{​d​e​l​s​}​ ​d​e​l​e​t​i​o​n​s​(​-​)
			 * @param {number} dels
			 * @param {number} inserts
			 */
			insertsDels: RequiredParams<'dels' | 'inserts'>
			/**
			 * (​n​e​w​ ​f​i​l​e​)
			 */
			newFile: string
			/**
			 * C​r​e​a​t​e​ ​t​h​i​s​ ​c​o​m​m​i​t​?
			 */
			createCommitPrompt: string
			/**
			 * C​o​m​m​i​t​ ​c​a​n​c​e​l​l​e​d
			 */
			commitCancelled: string
			/**
			 * C​r​e​a​t​i​n​g​ ​c​o​m​m​i​t​.​.​.
			 */
			creatingCommit: string
			/**
			 * C​o​m​m​i​t​ ​c​r​e​a​t​e​d​:​ ​{​n​a​m​e​}
			 * @param {string} name
			 */
			commitCreated: RequiredParams<'name'>
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​c​o​m​m​i​t
			 */
			commitCreateFailed: string
			/**
			 * P​u​s​h​ ​t​o​ ​r​e​m​o​t​e​ ​r​e​p​o​s​i​t​o​r​y​?
			 */
			pushPrompt: string
			/**
			 * C​o​m​m​i​t​ ​c​r​e​a​t​e​d​ ​l​o​c​a​l​l​y​.​ ​T​o​ ​p​u​s​h​ ​l​a​t​e​r​:
			 */
			pushLater: string
			/**
			 * P​u​s​h​i​n​g​ ​t​o​ ​r​e​m​o​t​e​.​.​.
			 */
			pushing: string
			/**
			 * B​r​a​n​c​h​ ​p​u​s​h​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y
			 */
			pushSuccess: string
			/**
			 * G​i​t​H​u​b​ ​C​L​I​ ​(​g​h​)​ ​d​e​t​e​c​t​e​d​ ​-​ ​c​a​n​ ​c​r​e​a​t​e​ ​P​R​ ​a​u​t​o​m​a​t​i​c​a​l​l​y
			 */
			ghDetected: string
			/**
			 * G​i​t​H​u​b​ ​C​L​I​ ​(​g​h​)​ ​n​o​t​ ​f​o​u​n​d​ ​-​ ​w​i​l​l​ ​p​r​o​v​i​d​e​ ​m​a​n​u​a​l​ ​i​n​s​t​r​u​c​t​i​o​n​s
			 */
			ghNotFound: string
			/**
			 * I​n​s​t​a​l​l​ ​g​h​:​ ​h​t​t​p​s​:​/​/​c​l​i​.​g​i​t​h​u​b​.​c​o​m​/
			 */
			ghInstallHint: string
			/**
			 * C​r​e​a​t​e​ ​P​R​ ​n​o​w​ ​u​s​i​n​g​ ​g​h​ ​C​L​I​?
			 */
			createPrPrompt: string
			/**
			 * S​h​o​w​ ​P​R​ ​c​r​e​a​t​i​o​n​ ​i​n​f​o​r​m​a​t​i​o​n​?
			 */
			showPrInfo: string
			/**
			 * C​r​e​a​t​i​n​g​ ​p​u​l​l​ ​r​e​q​u​e​s​t​ ​w​i​t​h​ ​g​h​ ​C​L​I​.​.​.
			 */
			creatingPr: string
			/**
			 * P​u​l​l​ ​r​e​q​u​e​s​t​ ​c​r​e​a​t​e​d
			 */
			prCreated: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​P​R​ ​w​i​t​h​ ​g​h​ ​C​L​I
			 */
			prCreateFailed: string
			/**
			 * P​l​e​a​s​e​ ​c​r​e​a​t​e​ ​P​R​ ​m​a​n​u​a​l​l​y​:
			 */
			createPrManually: string
			/**
			 * P​R​ ​I​n​f​o​r​m​a​t​i​o​n​ ​(​c​o​p​y​ ​a​n​d​ ​u​s​e​)​:
			 */
			prInfoTitle: string
		}
		heavyweight: {
			/**
			 * I​n​i​t​i​a​l​i​z​i​n​g​ ​h​e​a​v​y​w​e​i​g​h​t​ ​p​l​u​g​i​n​:​ ​{​n​a​m​e​}
			 * @param {string} name
			 */
			initializing: RequiredParams<'name'>
			/**
			 *  ​ ​B​a​c​k​i​n​g​ ​u​p​ ​{​c​o​u​n​t​}​ ​p​r​o​t​e​c​t​e​d​ ​f​i​l​e​(​s​)​.​.​.
			 * @param {number} count
			 */
			backingUp: RequiredParams<'count'>
			/**
			 *  ​ ​E​x​e​c​u​t​i​n​g​:​ ​{​c​o​m​m​a​n​d​}
			 * @param {string} command
			 */
			executing: RequiredParams<'command'>
			/**
			 *  ​ ​M​e​r​g​i​n​g​ ​p​r​o​t​e​c​t​e​d​ ​f​i​l​e​s​.​.​.
			 */
			merging: string
			/**
			 *  ​ ​ ​ ​M​e​r​g​e​d​:​ ​{​p​a​t​h​}
			 * @param {string} path
			 */
			merged: RequiredParams<'path'>
			/**
			 *  ​ ​P​l​u​g​i​n​ ​'​{​n​a​m​e​}​'​ ​i​n​i​t​i​a​l​i​z​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y
			 * @param {string} name
			 */
			initSuccess: RequiredParams<'name'>
			/**
			 *  ​ ​S​o​m​e​ ​f​i​l​e​s​ ​f​a​i​l​e​d​ ​t​o​ ​m​e​r​g​e​.​ ​R​e​s​t​o​r​i​n​g​ ​b​a​c​k​u​p​s​.​.​.
			 */
			mergeFailed: string
			/**
			 *  ​ ​ ​ ​R​e​s​t​o​r​e​d​:​ ​{​p​a​t​h​}
			 * @param {string} path
			 */
			restored: RequiredParams<'path'>
			/**
			 *  ​ ​ ​ ​R​e​m​o​v​e​d​:​ ​{​p​a​t​h​}
			 * @param {string} path
			 */
			removed: RequiredParams<'path'>
		}
		resourceWriter: {
			/**
			 * C​r​e​a​t​e​d​:​ ​{​p​a​t​h​}
			 * @param {string} path
			 */
			created: RequiredParams<'path'>
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​s​l​a​s​h​ ​c​o​m​m​a​n​d​ ​{​n​a​m​e​}​:​ ​{​e​r​r​o​r​}
			 * @param {string} error
			 * @param {string} name
			 */
			slashCommandFailed: RequiredParams<'error' | 'name'>
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​s​k​i​l​l​ ​{​n​a​m​e​}​:​ ​{​e​r​r​o​r​}
			 * @param {string} error
			 * @param {string} name
			 */
			skillFailed: RequiredParams<'error' | 'name'>
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​g​e​n​e​r​a​t​e​ ​o​u​t​p​u​t​s​ ​f​o​r​ ​{​p​l​u​g​i​n​}​:​ ​{​e​r​r​o​r​}
			 * @param {string} error
			 * @param {string} plugin
			 */
			outputsFailed: RequiredParams<'error' | 'plugin'>
		}
	}
}

export type TranslationFunctions = {
	common: {
		/**
		 * Yes
		 */
		yes: () => LocalizedString
		/**
		 * No
		 */
		no: () => LocalizedString
		/**
		 * Confirm
		 */
		confirm: () => LocalizedString
		/**
		 * Cancel
		 */
		cancel: () => LocalizedString
		/**
		 * Skip
		 */
		skip: () => LocalizedString
		/**
		 * Back
		 */
		back: () => LocalizedString
		/**
		 * Next
		 */
		next: () => LocalizedString
		/**
		 * Done
		 */
		done: () => LocalizedString
		/**
		 * enabled
		 */
		enabled: () => LocalizedString
		/**
		 * disabled
		 */
		disabled: () => LocalizedString
		/**
		 * Selected
		 */
		selected: () => LocalizedString
		/**
		 * Step {current}/{total}
		 */
		step: (arg: { current: number, total: number }) => LocalizedString
		/**
		 * {count} feature{{s}}
		 */
		features: (arg: { count: number }) => LocalizedString
	}
	cli: {
		/**
		 * claude-init
		 */
		name: () => LocalizedString
		/**
		 * Initialize Claude Agent system in your project
		 */
		description: () => LocalizedString
		commands: {
			init: {
				/**
				 * Initialize Claude Agent system (interactive)
				 */
				description: () => LocalizedString
				/**
				 * Force re-initialization (overwrite existing files)
				 */
				forceOption: () => LocalizedString
				/**
				 * Target directory (default: current directory)
				 */
				targetOption: () => LocalizedString
			}
		}
		errors: {
			/**
			 * Initialization failed:
			 */
			initFailed: () => LocalizedString
			/**
			 * Command failed:
			 */
			commandFailed: () => LocalizedString
			/**
			 * Fatal error:
			 */
			fatalError: () => LocalizedString
		}
	}
	dependency: {
		/**
		 * Checking dependencies...
		 */
		checking: () => LocalizedString
		/**
		 * [will install: {tools}]
		 */
		willInstall: (arg: { tools: string }) => LocalizedString
		/**
		 * missing required tools
		 */
		missing: () => LocalizedString
		/**
		 * Installing {name}...
		 */
		installing: (arg: { name: string }) => LocalizedString
		/**
		 * {name} installed
		 */
		installed: (arg: { name: string }) => LocalizedString
		/**
		 * Failed to install {name}: {error}
		 */
		installFailed: (arg: { error: string, name: string }) => LocalizedString
	}
	mcp: {
		/**
		 * Registering MCP servers...
		 */
		registering: () => LocalizedString
		/**
		 * Registered MCP server: {name}
		 */
		registered: (arg: { name: string }) => LocalizedString
		/**
		 * Failed to register MCP server {name}
		 */
		failed: (arg: { name: string }) => LocalizedString
	}
	initCommand: {
		/**
		 * Running initialization commands...
		 */
		running: () => LocalizedString
		/**
		 * {name}
		 */
		success: (arg: { name: string }) => LocalizedString
		/**
		 * {name} failed: {error}
		 */
		failed: (arg: { error: string, name: string }) => LocalizedString
		/**
		 * Skipped: {name}
		 */
		skipped: (arg: { name: string }) => LocalizedString
		/**
		 * Init commands: {success} succeeded, {failed} failed
		 */
		summary: (arg: { failed: number, success: number }) => LocalizedString
		/**
		 * Completed {count} initialization command(s)
		 */
		completed: (arg: { count: number }) => LocalizedString
	}
	prompts: {
		projectInfo: {
			/**
			 * Project Information
			 */
			stepTitle: () => LocalizedString
			/**
			 * Project name:
			 */
			namePrompt: () => LocalizedString
			/**
			 * Project name is required
			 */
			nameRequired: () => LocalizedString
			/**
			 * Project description:
			 */
			descPrompt: () => LocalizedString
			/**
			 * A project with Claude integration
			 */
			descDefault: () => LocalizedString
			/**
			 * Project description is required
			 */
			descRequired: () => LocalizedString
		}
		featureSelect: {
			/**
			 * Select Features
			 */
			stepTitle: () => LocalizedString
			/**
			 * What features do you want to enable?
			 */
			prompt: () => LocalizedString
			/**
			 * Note: Some features are "heavyweight" plugins that run their own initialization commands and may modify existing files.
			 */
			heavyweightNote: () => LocalizedString
			/**
			 * [heavyweight]
			 */
			heavyweightLabel: () => LocalizedString
			/**
			 * (conflicts with: {plugins})
			 */
			conflictsWith: (arg: { plugins: string }) => LocalizedString
			/**
			 * Selected: {count} feature{{s}}
			 */
			selectedCount: (arg: { count: number }) => LocalizedString
			/**
			 * Heavyweight plugins selected: {plugins}
			 */
			heavyweightWarning: (arg: { plugins: string }) => LocalizedString
			/**
			 * These will run external initialization commands.
			 */
			heavyweightWarningDetail: () => LocalizedString
		}
		conflictResolution: {
			/**
			 * Conflict resolution:
			 */
			title: () => LocalizedString
			/**
			 *   - Removed: {item}
			 */
			removed: (arg: { item: string }) => LocalizedString
		}
		pluginConfig: {
			/**
			 * Configure {plugin}
			 */
			stepTitle: (arg: { plugin: string }) => LocalizedString
			/**
			 * Plugin '{name}' not found. Skipping.
			 */
			notFound: (arg: { name: string }) => LocalizedString
		}
		summary: {
			/**
			 * Summary
			 */
			stepTitle: () => LocalizedString
			/**
			 * Project:
			 */
			project: () => LocalizedString
			/**
			 * Location:
			 */
			location: () => LocalizedString
			/**
			 * Features:
			 */
			features: () => LocalizedString
			/**
			 *   ✓ {name}
			 */
			featureItem: (arg: { name: string }) => LocalizedString
			/**
			 * Proceed with initialization?
			 */
			confirmPrompt: () => LocalizedString
		}
		alreadyInitialized: {
			/**
			 * This project is already initialized!
			 */
			warning: () => LocalizedString
			/**
			 * Project: {name}
			 */
			projectInfo: (arg: { name: string }) => LocalizedString
			/**
			 * Initialized: {date}
			 */
			initializedDate: (arg: { date: string }) => LocalizedString
			/**
			 * Version: {version}
			 */
			versionInfo: (arg: { version: string }) => LocalizedString
			/**
			 * What would you like to do?
			 */
			whatToDo: () => LocalizedString
			/**
			 * Keep existing setup
			 */
			keepOption: () => LocalizedString
			/**
			 * (no changes)
			 */
			keepDesc: () => LocalizedString
			/**
			 * Reconfigure
			 */
			reconfigOption: () => LocalizedString
			/**
			 * (modify settings)
			 */
			reconfigDesc: () => LocalizedString
			/**
			 * Reinitialize
			 */
			reinitOption: () => LocalizedString
			/**
			 * (start from scratch)
			 */
			reinitDesc: () => LocalizedString
			/**
			 * This will overwrite existing files. Are you sure?
			 */
			confirmOverwrite: () => LocalizedString
		}
		/**
		 * Initialization cancelled.
		 */
		cancelled: () => LocalizedString
		/**
		 * No plugins selected. Initialization cancelled.
		 */
		noPlugins: () => LocalizedString
		/**
		 * Keeping existing setup. No changes made.
		 */
		keepingSetup: () => LocalizedString
		/**
		 * Reconfiguration is not yet implemented.
		 */
		reconfigNotImpl: () => LocalizedString
		complete: {
			/**
			 * Initialization complete!
			 */
			title: () => LocalizedString
			/**
			 * Files created:
			 */
			filesCreated: () => LocalizedString
			/**
			 *   ✓ {filename}
			 */
			agentMd: (arg: { filename: string }) => LocalizedString
			/**
			 *   ✓ {dirname}/
			 */
			agentDir: (arg: { dirname: string }) => LocalizedString
			/**
			 * Available slash commands:
			 */
			slashCommands: () => LocalizedString
			/**
			 *   • /{name}{hint} - {description}
			 */
			commandItem: (arg: { description: string, hint: string, name: string }) => LocalizedString
			/**
			 * Next steps:
			 */
			nextSteps: () => LocalizedString
			/**
			 *   • Review {filename} and customize as needed
			 */
			step1: (arg: { filename: string }) => LocalizedString
			/**
			 *   • Start chatting with Claude in this project
			 */
			step2: () => LocalizedString
			/**
			 *   • Try slash commands like /memory-search or /task-status
			 */
			step3: () => LocalizedString
			/**
			 *   • Run 'claude-init --help' for more commands
			 */
			step4: () => LocalizedString
			/**
			 * MCP servers registered:
			 */
			mcpServers: () => LocalizedString
			/**
			 * Skills available:
			 */
			skillsAvailable: () => LocalizedString
			/**
			 * Manual steps required:
			 */
			manualStepsRequired: () => LocalizedString
			/**
			 * Optional steps:
			 */
			optionalSteps: () => LocalizedString
			/**
			 * Warnings:
			 */
			warnings: () => LocalizedString
			/**
			 * Plugin messages:
			 */
			pluginMessages: () => LocalizedString
			/**
			 * Dependencies installed:
			 */
			installedDeps: () => LocalizedString
		}
		progress: {
			/**
			 * Complete
			 */
			complete: () => LocalizedString
			/**
			 * Failed
			 */
			failed: () => LocalizedString
			/**
			 * Warning
			 */
			warning: () => LocalizedString
			/**
			 * Info
			 */
			info: () => LocalizedString
		}
	}
	plugins: {
		systemDetector: {
			/**
			 * system-detector
			 */
			name: () => LocalizedString
			/**
			 * Configure system environment with two-layer memory
			 */
			description: () => LocalizedString
			/**
			 * [System Configuration]
			 */
			configTitle: () => LocalizedString
			/**
			 * ✓ Found user preferences (~/.claude/)
			 */
			foundPrefs: () => LocalizedString
			/**
			 *   OS: {name} ({type})
			 */
			osInfo: (arg: { name: string, type: string }) => LocalizedString
			/**
			 *   Preferred Python manager: {manager}
			 */
			pythonManager: (arg: { manager: string }) => LocalizedString
			/**
			 *   Preferred Node manager: {manager}
			 */
			nodeManager: (arg: { manager: string }) => LocalizedString
			/**
			 * First time setup - detecting system...
			 */
			firstTimeSetup: () => LocalizedString
			/**
			 * ✓ OS: {name} ({type})
			 */
			osDetected: (arg: { name: string, type: string }) => LocalizedString
			/**
			 *   System package manager: {pm}
			 */
			systemPm: (arg: { pm: string }) => LocalizedString
			/**
			 * ✓ Timezone: {tz}
			 */
			timezone: (arg: { tz: string }) => LocalizedString
			/**
			 * ✓ Language: {lang}
			 */
			language: (arg: { lang: string }) => LocalizedString
			/**
			 * ✓ Python detected: {version}
			 */
			pythonDetected: (arg: { version: string }) => LocalizedString
			/**
			 *   Available managers: {list}
			 */
			availableManagers: (arg: { list: string }) => LocalizedString
			/**
			 *   → Using: {manager}
			 */
			using: (arg: { manager: string }) => LocalizedString
			/**
			 *   → Selected: {manager}
			 */
			pythonSelected: (arg: { manager: string }) => LocalizedString
			/**
			 * Select your preferred Python package manager:
			 */
			selectPython: () => LocalizedString
			/**
			 * Select your preferred Node.js package manager:
			 */
			selectNode: () => LocalizedString
			/**
			 * ✓ Node.js detected: {version}
			 */
			nodeDetected: (arg: { version: string }) => LocalizedString
			/**
			 *   → Selected: {manager}
			 */
			nodeSelected: (arg: { manager: string }) => LocalizedString
			/**
			 * [Project Configuration]
			 */
			projectConfig: () => LocalizedString
			/**
			 * Use your preferred managers for this project?
			 */
			usePreferred: () => LocalizedString
			/**
			 * Select Python package manager for this project:
			 */
			selectProjectPython: () => LocalizedString
			/**
			 * Select Node.js package manager for this project:
			 */
			selectProjectNode: () => LocalizedString
			/**
			 *   Python: {manager}
			 */
			pythonConfig: (arg: { manager: string }) => LocalizedString
			/**
			 *   Node: {manager}
			 */
			nodeConfig: (arg: { manager: string }) => LocalizedString
			/**
			 * (not configured)
			 */
			notConfigured: () => LocalizedString
			/**
			 * User preferences saved to ~/.claude/system/preferences.toon
			 */
			userPrefsSaved: () => LocalizedString
			/**
			 * Project configuration saved to .agent/system/config.toon
			 */
			projectConfigSaved: () => LocalizedString
			pmDesc: {
				/**
				 * Standard Python package installer
				 */
				pip: () => LocalizedString
				/**
				 * ⚡ Ultra-fast Python package installer (recommended)
				 */
				uv: () => LocalizedString
				/**
				 * 📦 Dependency management and packaging
				 */
				poetry: () => LocalizedString
				/**
				 * 🔧 Virtual environments and dependencies
				 */
				pipenv: () => LocalizedString
				/**
				 * 🐍 Package and environment management
				 */
				conda: () => LocalizedString
				/**
				 * 📦 Standard Node.js package manager
				 */
				npm: () => LocalizedString
				/**
				 * ⚡ Fast, disk space efficient (recommended)
				 */
				pnpm: () => LocalizedString
				/**
				 * 🧶 Fast, reliable, secure dependency manager
				 */
				yarn: () => LocalizedString
				/**
				 * 🔥 All-in-one JavaScript runtime and toolkit
				 */
				bun: () => LocalizedString
			}
		}
		memorySystem: {
			/**
			 * memory-system
			 */
			name: () => LocalizedString
			/**
			 * Memory system for knowledge persistence
			 */
			description: () => LocalizedString
			/**
			 * Which memory types do you want to enable?
			 */
			selectTypes: () => LocalizedString
			/**
			 * Knowledge
			 */
			knowledge: () => LocalizedString
			/**
			 * Stable architectural knowledge
			 */
			knowledgeDesc: () => LocalizedString
			/**
			 * History
			 */
			history: () => LocalizedString
			/**
			 * Task history records
			 */
			historyDesc: () => LocalizedString
			/**
			 * Include system knowledge layer (universal tools, standards)?
			 */
			includeSystem: () => LocalizedString
			/**
			 * Memory types: {types}
			 */
			typesSelected: (arg: { types: string }) => LocalizedString
			/**
			 * System knowledge: included
			 */
			systemIncluded: () => LocalizedString
			/**
			 * Memory system initialized
			 */
			initialized: () => LocalizedString
			commands: {
				/**
				 * Find notes by tag
				 */
				searchDesc: () => LocalizedString
				/**
				 * Query notes by topic
				 */
				queryDesc: () => LocalizedString
				/**
				 * Show complete memory index
				 */
				indexDesc: () => LocalizedString
				/**
				 * Show N recent notes
				 */
				recentDesc: () => LocalizedString
			}
		}
		git: {
			/**
			 * git
			 */
			name: () => LocalizedString
			/**
			 * Git operations and auto-commit
			 */
			description: () => LocalizedString
			/**
			 * Enable auto-commit for memory system updates?
			 */
			enableAutoCommit: () => LocalizedString
			/**
			 * Commit memory files separately from other changes?
			 */
			separateCommits: () => LocalizedString
			/**
			 * Enable remote sync for system memory?
			 */
			enableRemoteSync: () => LocalizedString
			/**
			 * Remote template repository URL:
			 */
			remoteUrl: () => LocalizedString
			/**
			 * Auto-create PRs when syncing?
			 */
			autoCreatePr: () => LocalizedString
			/**
			 * Allow AI agent to perform git operations?
			 */
			allowAiGit: () => LocalizedString
			/**
			 * Auto-commit: enabled
			 */
			autoCommitEnabled: () => LocalizedString
			/**
			 * Remote sync: enabled
			 */
			remoteSyncEnabled: () => LocalizedString
			/**
			 * AI git ops: allowed
			 */
			aiGitAllowed: () => LocalizedString
			/**
			 * AI git ops: forbidden
			 */
			aiGitForbidden: () => LocalizedString
			/**
			 * Git configuration stored
			 */
			configStored: () => LocalizedString
		}
		taskSystem: {
			/**
			 * task-system
			 */
			name: () => LocalizedString
			/**
			 * Task workflows, state tracking, and outputs
			 */
			description: () => LocalizedString
			/**
			 * Enable task state tracking (current.toon)?
			 */
			enableTracking: () => LocalizedString
			/**
			 * Enable task output directory (.agent/tasks/output/)?
			 */
			enableOutput: () => LocalizedString
			/**
			 * Task tracking: enabled
			 */
			trackingEnabled: () => LocalizedString
			/**
			 * Output directory: enabled
			 */
			outputEnabled: () => LocalizedString
			/**
			 * Task system initialized
			 */
			initialized: () => LocalizedString
			commands: {
				/**
				 * Create task with dedicated prompt
				 */
				createDesc: () => LocalizedString
				/**
				 * Start executing a task
				 */
				startDesc: () => LocalizedString
				/**
				 * Pause current task (save state)
				 */
				pauseDesc: () => LocalizedString
				/**
				 * Resume a paused task
				 */
				resumeDesc: () => LocalizedString
				/**
				 * Show current task state
				 */
				statusDesc: () => LocalizedString
				/**
				 * List all tasks
				 */
				listDesc: () => LocalizedString
				/**
				 * List unfinished tasks
				 */
				incompleteDesc: () => LocalizedString
				/**
				 * Mark task as complete
				 */
				completeDesc: () => LocalizedString
			}
		}
		promptPresets: {
			/**
			 * prompt-presets
			 */
			name: () => LocalizedString
			/**
			 * Base prompt templates with optional enhancements
			 */
			description: () => LocalizedString
			/**
			 * [Prompt Presets]
			 */
			configTitle: () => LocalizedString
			/**
			 * Select a base prompt template:
			 */
			selectBase: () => LocalizedString
			/**
			 * ✓ Selected base: {name}
			 */
			selectedBase: (arg: { name: string }) => LocalizedString
			/**
			 * Select enhancement modules to include (optional):
			 */
			selectEnhancements: () => LocalizedString
			/**
			 * ✓ Selected enhancements: {list}
			 */
			selectedEnhancements: (arg: { list: string }) => LocalizedString
			/**
			 * ✓ No enhancements selected (minimal preset)
			 */
			noEnhancements: () => LocalizedString
			/**
			 * Base: {name}
			 */
			baseLabel: (arg: { name: string }) => LocalizedString
			/**
			 * Enhancements ({count}): {list}
			 */
			enhancementsLabel: (arg: { count: number, list: string }) => LocalizedString
			/**
			 * Enhancements: none (minimal)
			 */
			enhancementsNone: () => LocalizedString
			/**
			 * Prompt preset will be generated
			 */
			willGenerate: () => LocalizedString
			/**
			 * Warning: Enhancement {name} not found
			 */
			enhancementNotFound: (arg: { name: string }) => LocalizedString
			/**
			 * Failed to generate preset: {error}
			 */
			generateFailed: (arg: { error: string }) => LocalizedString
			bases: {
				codeReview: {
					/**
					 * Code Review
					 */
					name: () => LocalizedString
					/**
					 * Code quality and security review
					 */
					desc: () => LocalizedString
				}
				documentation: {
					/**
					 * Documentation
					 */
					name: () => LocalizedString
					/**
					 * Generate and maintain docs
					 */
					desc: () => LocalizedString
				}
				refactoring: {
					/**
					 * Refactoring
					 */
					name: () => LocalizedString
					/**
					 * Code improvement and cleanup
					 */
					desc: () => LocalizedString
				}
				testing: {
					/**
					 * Testing
					 */
					name: () => LocalizedString
					/**
					 * Test generation and quality
					 */
					desc: () => LocalizedString
				}
				architecture: {
					/**
					 * Architecture
					 */
					name: () => LocalizedString
					/**
					 * System design analysis
					 */
					desc: () => LocalizedString
				}
				bugFixing: {
					/**
					 * Bug Fixing
					 */
					name: () => LocalizedString
					/**
					 * Debugging and troubleshooting
					 */
					desc: () => LocalizedString
				}
			}
			enhancements: {
				systemInfo: {
					/**
					 * System Information
					 */
					name: () => LocalizedString
					/**
					 * OS, Python, Node.js environment
					 */
					desc: () => LocalizedString
				}
				memoryInstructions: {
					/**
					 * Memory Instructions
					 */
					name: () => LocalizedString
					/**
					 * How to use memory system
					 */
					desc: () => LocalizedString
				}
				fullContext: {
					/**
					 * Full Context Reading
					 */
					name: () => LocalizedString
					/**
					 * Read files completely, use all available tokens
					 */
					desc: () => LocalizedString
				}
				gitRules: {
					/**
					 * Git Rules
					 */
					name: () => LocalizedString
					/**
					 * Git operation guidelines
					 */
					desc: () => LocalizedString
				}
				taskWorkflow: {
					/**
					 * Task Workflow
					 */
					name: () => LocalizedString
					/**
					 * Task management instructions
					 */
					desc: () => LocalizedString
				}
				toonRef: {
					/**
					 * TOON Reference
					 */
					name: () => LocalizedString
					/**
					 * TOON format quick reference
					 */
					desc: () => LocalizedString
				}
			}
		}
		claudeFlow: {
			/**
			 * claude-flow
			 */
			name: () => LocalizedString
			/**
			 * Claude Flow integration for AI orchestration with multi-agent support
			 */
			description: () => LocalizedString
			/**
			 * Select Claude Flow initialization mode:
			 */
			selectMode: () => LocalizedString
			modes: {
				standard: {
					/**
					 * Standard
					 */
					name: () => LocalizedString
					/**
					 * Full setup with common workflows and 54+ agents
					 */
					desc: () => LocalizedString
				}
				sparc: {
					/**
					 * SPARC
					 */
					name: () => LocalizedString
					/**
					 * SPARC methodology with structured development phases
					 */
					desc: () => LocalizedString
				}
				minimal: {
					/**
					 * Minimal
					 */
					name: () => LocalizedString
					/**
					 * Essential files only, basic agent setup
					 */
					desc: () => LocalizedString
				}
				skip: {
					/**
					 * Skip
					 */
					name: () => LocalizedString
					/**
					 * Skip Claude Flow initialization
					 */
					desc: () => LocalizedString
				}
			}
			/**
			 * Enable Swarm Mode (multi-agent orchestration)?
			 */
			enableSwarm: () => LocalizedString
			/**
			 * Enable Hive Mind System (collective intelligence)?
			 */
			enableHiveMind: () => LocalizedString
			/**
			 * Select MCP servers to configure:
			 */
			selectMcp: () => LocalizedString
			mcpServers: {
				claudeFlow: {
					/**
					 * claude-flow
					 */
					name: () => LocalizedString
					/**
					 * Core Claude Flow MCP server (required)
					 */
					desc: () => LocalizedString
				}
				ruvSwarm: {
					/**
					 * ruv-swarm
					 */
					name: () => LocalizedString
					/**
					 * Enhanced swarm coordination
					 */
					desc: () => LocalizedString
				}
				flowNexus: {
					/**
					 * flow-nexus
					 */
					name: () => LocalizedString
					/**
					 * Cloud features and advanced orchestration
					 */
					desc: () => LocalizedString
				}
			}
			/**
			 * Claude Flow: Skipped
			 */
			skipped: () => LocalizedString
			/**
			 * Mode: {mode}
			 */
			modeSelected: (arg: { mode: string }) => LocalizedString
			/**
			 * Swarm Mode: enabled
			 */
			swarmEnabled: () => LocalizedString
			/**
			 * Hive Mind: enabled
			 */
			hiveMindEnabled: () => LocalizedString
			/**
			 * MCP Servers: {list}
			 */
			mcpSelected: (arg: { list: string }) => LocalizedString
			/**
			 * Show Claude Flow status
			 */
			statusDesc: () => LocalizedString
		}
		pmaGh: {
			/**
			 * pma-gh
			 */
			name: () => LocalizedString
			/**
			 * GitHub project management assistant with issue tracking and PR workflow
			 */
			description: () => LocalizedString
			/**
			 * [PMA-GH Configuration]
			 */
			configTitle: () => LocalizedString
			/**
			 * Enable issue validation (check assignee and project linkage)?
			 */
			enableValidation: () => LocalizedString
			/**
			 * Automatically create feature branch when starting an issue?
			 */
			autoCreateBranch: () => LocalizedString
			/**
			 * Branch naming pattern:
			 */
			branchPattern: () => LocalizedString
			/**
			 * Validation: enabled
			 */
			validationEnabled: () => LocalizedString
			/**
			 * Validation: disabled
			 */
			validationDisabled: () => LocalizedString
			/**
			 * Auto branch: enabled
			 */
			autoBranchEnabled: () => LocalizedString
			/**
			 * Auto branch: disabled
			 */
			autoBranchDisabled: () => LocalizedString
			/**
			 * Branch pattern: {pattern}
			 */
			branchPatternLabel: (arg: { pattern: string }) => LocalizedString
			/**
			 * PMA-GH plugin initialized
			 */
			initialized: () => LocalizedString
			commands: {
				/**
				 * Fetch, validate, and analyze a GitHub issue
				 */
				issueDesc: () => LocalizedString
				/**
				 * Create a Pull Request to resolve the current issue
				 */
				prDesc: () => LocalizedString
				/**
				 * Close the current issue as not planned
				 */
				closeDesc: () => LocalizedString
			}
		}
		languageSettings: {
			/**
			 * language-settings
			 */
			name: () => LocalizedString
			/**
			 * Configure LLM Agent language preferences
			 */
			description: () => LocalizedString
			/**
			 * [Language Settings]
			 */
			configTitle: () => LocalizedString
			/**
			 * ✓ Detected language: {language}
			 */
			detected: (arg: { language: string }) => LocalizedString
			/**
			 * What language should the AI use for outputs (documentation, reports)?
			 */
			selectUserLanguage: () => LocalizedString
			/**
			 * What language should the AI use for internal thinking?
			 */
			selectThinkLanguage: () => LocalizedString
			/**
			 * (detected from system)
			 */
			detectedHint: () => LocalizedString
			/**
			 * Recommended for technical work (code, docs are usually in English)
			 */
			thinkEnglishDesc: () => LocalizedString
			/**
			 * Same as output language
			 */
			sameAsUser: () => LocalizedString
			/**
			 * Use the same language for thinking and outputs
			 */
			sameAsUserDesc: () => LocalizedString
			/**
			 * Think language: {language}
			 */
			thinkLabel: (arg: { language: string }) => LocalizedString
			/**
			 * Output language: {language}
			 */
			userLabel: (arg: { language: string }) => LocalizedString
		}
	}
	errors: {
		validation: {
			/**
			 * Config file not found. Run "claude-memory-init init" first.
			 */
			configNotFound: () => LocalizedString
			/**
			 * Invalid config key: {key}
			 */
			invalidKey: (arg: { key: string }) => LocalizedString
			/**
			 * Invalid index: {index}. Valid range: 0-{max}
			 */
			invalidIndex: (arg: { index: number, max: number }) => LocalizedString
		}
		plugin: {
			/**
			 * Plugin with name '{name}' is already registered
			 */
			alreadyRegistered: (arg: { name: string }) => LocalizedString
			/**
			 * Plugin commandName '{name}' is already used by plugin '{existing}'
			 */
			commandNameUsed: (arg: { existing: string, name: string }) => LocalizedString
			/**
			 * Plugin '{name}' not found in registry
			 */
			notFound: (arg: { name: string }) => LocalizedString
			/**
			 * Plugin must have metadata
			 */
			mustHaveMeta: () => LocalizedString
			/**
			 * Plugin must have a valid name
			 */
			mustHaveName: () => LocalizedString
			/**
			 * Plugin '{name}' must have a valid commandName
			 */
			mustHaveCommand: (arg: { name: string }) => LocalizedString
			/**
			 * Plugin '{name}' must have a valid version
			 */
			mustHaveVersion: (arg: { name: string }) => LocalizedString
			/**
			 * Plugin '{name}' must have a description
			 */
			mustHaveDesc: (arg: { name: string }) => LocalizedString
			/**
			 * Plugin '{name}' failed during '{hook}' hook: {error}
			 */
			hookFailed: (arg: { error: string, hook: string, name: string }) => LocalizedString
			/**
			 * Plugin dependency not found: {plugin}
			 */
			dependencyNotFound: (arg: { plugin: string }) => LocalizedString
		}
		heavyweight: {
			/**
			 * Plugin '{name}' is marked as heavyweight but doesn't implement getHeavyweightConfig()
			 */
			noConfig: (arg: { name: string }) => LocalizedString
			/**
			 * Failed to get heavyweight config for '{name}': {error}
			 */
			configFailed: (arg: { error: string, name: string }) => LocalizedString
			/**
			 * Failed to backup protected files: {error}
			 */
			backupFailed: (arg: { error: string }) => LocalizedString
			/**
			 * Command exited with code {code}
			 */
			commandExitCode: (arg: { code: number }) => LocalizedString
			/**
			 * Command failed: {error}
			 */
			commandFailed: (arg: { error: string }) => LocalizedString
			/**
			 * Failed to merge: {path} - {error}
			 */
			mergeFailed: (arg: { error: string, path: string }) => LocalizedString
			/**
			 * Unknown merge strategy: {strategy}
			 */
			unknownStrategy: (arg: { strategy: string }) => LocalizedString
		}
		git: {
			/**
			 * Not a git repository. Skipping auto-commit.
			 */
			notRepo: () => LocalizedString
			/**
			 * Failed to commit memory system changes
			 */
			commitFailed: () => LocalizedString
			/**
			 * Push failed
			 */
			pushFailed: () => LocalizedString
		}
		file: {
			/**
			 * Failed to load config from {path}: {message}
			 */
			loadFailed: (arg: { message: string, path: string }) => LocalizedString
			/**
			 * Failed to save config to {path}: {message}
			 */
			saveFailed: (arg: { message: string, path: string }) => LocalizedString
			/**
			 * Failed to create {path}: {error}
			 */
			createFailed: (arg: { error: string, path: string }) => LocalizedString
		}
	}
	utils: {
		autoCommit: {
			/**
			 * No changes to commit
			 */
			noChanges: () => LocalizedString
			/**
			 * No memory system changes to commit
			 */
			noMemoryChanges: () => LocalizedString
			/**
			 * Auto-committing changes...
			 */
			committing: () => LocalizedString
			/**
			 * Committing {count} memory system file(s) separately...
			 */
			committingSeparate: (arg: { count: number }) => LocalizedString
			/**
			 * Committing {count} memory system file(s)...
			 */
			committingCombined: (arg: { count: number }) => LocalizedString
			/**
			 * Memory system changes committed
			 */
			committed: () => LocalizedString
			/**
			 * Files committed:
			 */
			filesCommitted: () => LocalizedString
			/**
			 * Note: {count} other file(s) remain uncommitted:
			 */
			otherFilesRemain: (arg: { count: number }) => LocalizedString
			/**
			 * Commit these files manually or they will be included in the next commit
			 */
			commitManually: () => LocalizedString
		}
		gitOps: {
			/**
			 * Initializing git submodule: {path}
			 */
			initSubmodule: (arg: { path: string }) => LocalizedString
			/**
			 * Updating git submodule: {path}
			 */
			updateSubmodule: (arg: { path: string }) => LocalizedString
			/**
			 * {path} exists but is not a git submodule
			 */
			notSubmodule: (arg: { path: string }) => LocalizedString
			/**
			 * Cloning memory repo to temporary directory...
			 */
			cloning: () => LocalizedString
			/**
			 * Found {count} file(s) with differences
			 */
			foundDiffs: (arg: { count: number }) => LocalizedString
			/**
			 * No differences found between local and remote memory repos
			 */
			noDiffs: () => LocalizedString
			/**
			 * Creating branch: {name}
			 */
			creatingBranch: (arg: { name: string }) => LocalizedString
			/**
			 * Branch '{name}' created with {count} system memory file(s)
			 */
			branchCreated: (arg: { count: number, name: string }) => LocalizedString
			/**
			 * Files included in this PR:
			 */
			filesIncluded: () => LocalizedString
			/**
			 * PR label: 
			 */
			prLabel: () => LocalizedString
			/**
			 * Next steps:
			 */
			nextStepsTitle: () => LocalizedString
			/**
			 * COMMIT PREVIEW
			 */
			commitPreview: () => LocalizedString
			/**
			 * Commit Message:
			 */
			commitMessage: () => LocalizedString
			/**
			 * File Changes:
			 */
			fileChanges: () => LocalizedString
			/**
			 * {inserts} insertions(+), {dels} deletions(-)
			 */
			insertsDels: (arg: { dels: number, inserts: number }) => LocalizedString
			/**
			 * (new file)
			 */
			newFile: () => LocalizedString
			/**
			 * Create this commit?
			 */
			createCommitPrompt: () => LocalizedString
			/**
			 * Commit cancelled
			 */
			commitCancelled: () => LocalizedString
			/**
			 * Creating commit...
			 */
			creatingCommit: () => LocalizedString
			/**
			 * Commit created: {name}
			 */
			commitCreated: (arg: { name: string }) => LocalizedString
			/**
			 * Failed to create commit
			 */
			commitCreateFailed: () => LocalizedString
			/**
			 * Push to remote repository?
			 */
			pushPrompt: () => LocalizedString
			/**
			 * Commit created locally. To push later:
			 */
			pushLater: () => LocalizedString
			/**
			 * Pushing to remote...
			 */
			pushing: () => LocalizedString
			/**
			 * Branch pushed successfully
			 */
			pushSuccess: () => LocalizedString
			/**
			 * GitHub CLI (gh) detected - can create PR automatically
			 */
			ghDetected: () => LocalizedString
			/**
			 * GitHub CLI (gh) not found - will provide manual instructions
			 */
			ghNotFound: () => LocalizedString
			/**
			 * Install gh: https://cli.github.com/
			 */
			ghInstallHint: () => LocalizedString
			/**
			 * Create PR now using gh CLI?
			 */
			createPrPrompt: () => LocalizedString
			/**
			 * Show PR creation information?
			 */
			showPrInfo: () => LocalizedString
			/**
			 * Creating pull request with gh CLI...
			 */
			creatingPr: () => LocalizedString
			/**
			 * Pull request created
			 */
			prCreated: () => LocalizedString
			/**
			 * Failed to create PR with gh CLI
			 */
			prCreateFailed: () => LocalizedString
			/**
			 * Please create PR manually:
			 */
			createPrManually: () => LocalizedString
			/**
			 * PR Information (copy and use):
			 */
			prInfoTitle: () => LocalizedString
		}
		heavyweight: {
			/**
			 * Initializing heavyweight plugin: {name}
			 */
			initializing: (arg: { name: string }) => LocalizedString
			/**
			 *   Backing up {count} protected file(s)...
			 */
			backingUp: (arg: { count: number }) => LocalizedString
			/**
			 *   Executing: {command}
			 */
			executing: (arg: { command: string }) => LocalizedString
			/**
			 *   Merging protected files...
			 */
			merging: () => LocalizedString
			/**
			 *     Merged: {path}
			 */
			merged: (arg: { path: string }) => LocalizedString
			/**
			 *   Plugin '{name}' initialized successfully
			 */
			initSuccess: (arg: { name: string }) => LocalizedString
			/**
			 *   Some files failed to merge. Restoring backups...
			 */
			mergeFailed: () => LocalizedString
			/**
			 *     Restored: {path}
			 */
			restored: (arg: { path: string }) => LocalizedString
			/**
			 *     Removed: {path}
			 */
			removed: (arg: { path: string }) => LocalizedString
		}
		resourceWriter: {
			/**
			 * Created: {path}
			 */
			created: (arg: { path: string }) => LocalizedString
			/**
			 * Failed to create slash command {name}: {error}
			 */
			slashCommandFailed: (arg: { error: string, name: string }) => LocalizedString
			/**
			 * Failed to create skill {name}: {error}
			 */
			skillFailed: (arg: { error: string, name: string }) => LocalizedString
			/**
			 * Failed to generate outputs for {plugin}: {error}
			 */
			outputsFailed: (arg: { error: string, plugin: string }) => LocalizedString
		}
	}
}

export type Formatters = {}
